### ISSUE TITLE
Event based workflows on K8S keep running like daemon workflows

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#1020]
Vamp 0.9.5
Kubernetes 1.6
Running on Azure ACS

Triggering an event based workflow on Kubernetes with Vamp 0.9.5 actually creates a daemon workflow. This is due to the fact that Vamp doesn't set the VAMP_WORKFLOW_EXECUTION_PERIOD to 0.

![image](https://user-images.githubusercontent.com/3802923/29621181-52f3af3c-8820-11e7-8fca-490b0552bf9f.png)

Looking at the the code at https://github.com/magneticio/vamp-workflow-agent/blob/master/run.go#L16 "one shot workflows" only work when this value is set to 0.

On every trigger, a new job and a new pod is created. In this screenshot we just triggered the event twice:

![image](https://user-images.githubusercontent.com/3802923/29621790-02af031c-8822-11e7-9b35-9886f8987b15.png)

This can be reproduced with:

breed
```yaml
---
name: event-based-trigger
deployable:
  type: application/javascript
  definition: |
    'use strict';
    console.log('hello world')
```
   
workflow
```yaml
---
kind: workflow
name: event-based-trigger
breed: event-based-trigger
schedule:
  event: mytrigger
```
And then trigger and event with

```bash
curl -H "Content-Type: application/json" -X POST -d '{ "tags" : ["mytrigger"]}' http://<vamp_host>:8080/api/v1/events
```
