### ISSUE TITLE
Event based triggers are always reported as "restarting"

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#1032]
Any trigger created with `schedule: event` is shown as restarting in the UI and API

vamp: 0.9.5-1237-g7000ce10
platform: DC/OS 
```
Tims-MBP:vamp-cli tim$ vamp list workflows
 NAME                  SCHEDULE   STATUS       BREED               
 kibana                daemon     running      kibana              
 allocation            daemon     running      allocation          
 metrics               daemon     running      metrics             
 health                daemon     running      health              
 event-based-trigger   event      restarting   event-based-trigger 
 vga                   daemon     running      vga     
```
Reproduce with the following workflow and breeds

```yaml
name: event-based-trigger
kind: workflow
metadata: {}
breed:
  reference: event-based-trigger
status: restarting
schedule:
  event:
    tags:
    - mytrigger
environment_variables:
  VAMP_NAMESPACE: vamp
  VAMP_WORKFLOW_EXECUTION_TIMEOUT: '10'
  VAMP_KEY_VALUE_STORE_CONNECTION: zk-1.zk:2181
  VAMP_KEY_VALUE_STORE_PATH: /vamp/vamp/workflows/event-based-trigger
  VAMP_WORKFLOW_EXECUTION_PERIOD: '0'
  VAMP_API_TOKEN: ''
  VAMP_ELASTICSEARCH_URL: http://elasticsearch.marathon.mesos:9200
  VAMP_KEY_VALUE_STORE_TYPE: zookeeper
  VAMP_URL: http://10.20.0.100:8080
scale:
  cpu: 0.1
  memory: 128.00MB
  instances: 1
network: BRIDGE
arguments:
- privileged: 'true'
instances:
- name: event-based-trigger
  host: ''
  ports: {}
  deployed: true
  metadata: {}
```

```yaml
name: event-based-trigger
kind: breed
metadata: {}
deployable:
  type: application/javascript
  definition: |
    'use strict';
    console.log('this message comes from an event based trigger')
ports: {}
environment_variables: {}
constants: {}
arguments: []
dependencies: {}
```
