### ISSUE TITLE
Initial HTTP requests fail with 503 on edge router without HTTP KeepAlive

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#1033]
As far as I can see, every first HTTP request that does NOT use HTTP KeepAlive to a Vamp managed service fails. This is noticeable even with simple static html pages in a browser.

Reproduce with the following:

DC/OS: 1.9.0
Vamp: 0.9.5-1237-g7000ce10

```yaml
name: simpleservice:1.0.0
gateways:
  80/http: simpleservice/web
clusters:
  simpleservice:
    services:
      breed:
        name: simpleservice:1.0.0
        deployable: magneticio/simpleservice:1.0.0
        ports:
          web: 3000/http
      scale:
        cpu: 0.2
        memory: 128MB
        instances: 1
```

deploy the blueprint. Now hit the external gateway with some requests. In a browser you will see 503 on occasion. When the 503's stop, and you have a nice page you just have to wait a bit and it will happen again: the exact time is determined by the http keepalive timeout setting on the server and in the browser.

automatic reproduction can be done with apache bench:

```
# 100 requests, no concurrency
ab -n 100 -c 1 http://52.166.151.31/
...
Complete requests:      100
Failed requests:        61
...
```

```
# 100 requests, no concurrency with keep alive
ab -n 100 -c 1 -k http://52.166.151.31/
...
Failed requests:        0
Keep-Alive requests:    100
...
```
