### ISSUE TITLE
uppercase characters in deployment name creates internal gateway issue

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#1060]
when creating a deployment with uppercase characters (f.e. vampSLA) this is changed into a route vamp_sla but the internal gateway doesn't have the underscore and thus the deployment never finishes as the mapping between external and internal gateway cannot be resolved. 

How to reproduce: use this blueprint and deploy as "vampSLA"
```
---
name: savaSLA

gateways:
  9060: sava/webport

clusters:

  sava:
    breed:
      name: sava:1.0.0
      deployable: magneticio/sava:1.0.0
      ports:
        webport: 8080

    scale:
      cpu: 0.1
      memory: 128MB
      instances: 1

    sla:
      type: response_time_sliding_window
      threshold:
        upper: 1000
        lower: 100
      window:
        interval: 600
        cooldown: 600

      escalations:
        -
          type: scale_instances
          minimum: 1
          maximum: 10
          scale_by: 2 
```
