### ISSUE TITLE
deployment status failed issue

### ISSUE THREAD

**Issue by bench87** [magneticio/vamp#1096]
even though my container health is good and it is accepting request for health but vamp UI that contaner status is failed
![2018-03-08 11 24 00](https://user-images.githubusercontent.com/1912703/37129629-3e6e3fe4-22c3-11e8-91ad-ab2abe758f18.png)
![2018-03-08 11 24 36](https://user-images.githubusercontent.com/1912703/37129661-58e971d6-22c3-11e8-9d63-237c0bbd2892.png)

**Comment by olafmol** [comment]
Can you share vamp logs and blueprints? Any indication on when this happened, what triggered this, how to reproduce?

**Comment by bench87** [comment]
@olafmol I am investigating to reproduce

**Comment by harmw** [comment]
what are you using as endpoints for marathon and mesos? as this issue looks very familiar :)

**Comment by harmw** [comment]
as far as logging is concerned, I get a healthy gateway:
```
[36m19:41:15.665[0;39m [34m| INFO  | i.v.o.g.GatewaySynchronizationActor      | r/govamp/gateway-synchronization-actor-9 | Gateway event: blaze-sparrow-service/gateway - deployed
```

Followed by lots of these:
```
[0;39m[36m19:50:22.280[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | Deploying JObject(List((container,JObject(List((docker,JObject(List((parameters,JArray(List(JObject(List((key,JString(user)), (value,JString(498:498)))), JObject(List((key,JString(log-opt)), (value,JString(tag=docker.blaze-sparrow-service)))), JObject(List((key,JString(log-driver)), (value,JString(fluentd)))), JObject(List((key,JString(label)), (value,JString(role=sparrow)))), JObject(List((key,JString(label)), (value,JString(team=Checkout)))), JObject(List((key,JString(log-opt)), (value,JString(labels=team))))))), (image,JString(wehkamp/blaze-sparrow-service:27-414d5b3)), (portMappings,JArray(List(JObject(List((containerPort,JInt(5000)), (hostPort,JInt(0)), (protocol,JString(tcp))))))), (privileged,JBool(true)), (network,JString(BRIDGE))))), (type,JString(DOCKER))))), (healthChecks,JArray(List(JObject(List((timeoutSeconds,JInt(10)), (path,JString(/status)), (portIndex,JInt(0)), (gracePeriodSeconds,JInt(30)), (maxConsecutiveFailures,JInt(3)), (intervalSeconds,JInt(60)), (protocol,JString(HTTP))))))), (labels,JObject(List((io.vamp.deployment,JString(blaze-sparrow-service)), (io.vamp.cluster,JString(blaze-sparrow-service)), (io.vamp.service,JString(blaze-sparrow-service:27-414d5b3))))), (uris,JArray(List(JString(file:///etc/.dockercfg)))), (id,JString(/govamp/deployment-blaze-sparrow-service-service-36f623682f06ebaca1dddd55b8b0066e4bd9d926)), (instances,JInt(1)), (cpus,JDouble(0.1)), (mem,JInt(500)), (env,JObject(List((LOG_JSON_TCP_HOST,JString(logging.blaze:5170)), (SERVICE_NAME,JString(blaze-sparrow-service)), (SERVICE_TAGS,JString(vamp-managed))))), (constraints,JArray(List()))))
[0;39m[36m19:50:32.280[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | marathon update service: blaze-sparrow-service / wehkamp/blaze-sparrow-service:27-414d5b3
[0;39m[36m19:50:32.280[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | Deploying JObject(List((container,JObject(List((docker,JObject(List((parameters,JArray(List(JObject(List((key,JString(user)), (value,JString(498:498)))), JObject(List((key,JString(log-opt)), (value,JString(tag=docker.blaze-sparrow-service)))), JObject(List((key,JString(log-driver)), (value,JString(fluentd)))), JObject(List((key,JString(label)), (value,JString(role=sparrow)))), JObject(List((key,JString(label)), (value,JString(team=Checkout)))), JObject(List((key,JString(log-opt)), (value,JString(labels=team))))))), (image,JString(wehkamp/blaze-sparrow-service:27-414d5b3)), (portMappings,JArray(List(JObject(List((containerPort,JInt(5000)), (hostPort,JInt(0)), (protocol,JString(tcp))))))), (privileged,JBool(true)), (network,JString(BRIDGE))))), (type,JString(DOCKER))))), (healthChecks,JArray(List(JObject(List((timeoutSeconds,JInt(10)), (path,JString(/status)), (portIndex,JInt(0)), (gracePeriodSeconds,JInt(30)), (maxConsecutiveFailures,JInt(3)), (intervalSeconds,JInt(60)), (protocol,JString(HTTP))))))), (labels,JObject(List((io.vamp.deployment,JString(blaze-sparrow-service)), (io.vamp.cluster,JString(blaze-sparrow-service)), (io.vamp.service,JString(blaze-sparrow-service:27-414d5b3))))), (uris,JArray(List(JString(file:///etc/.dockercfg)))), (id,JString(/govamp/deployment-blaze-sparrow-service-service-36f623682f06ebaca1dddd55b8b0066e4bd9d926)), (instances,JInt(1)), (cpus,JDouble(0.1)), (mem,JInt(500)), (env,JObject(List((LOG_JSON_TCP_HOST,JString(logging.blaze:5170)), (SERVICE_NAME,JString(blaze-sparrow-service)), (SERVICE_TAGS,JString(vamp-managed))))), (constraints,JArray(List()))))
[0;39m[36m19:50:42.279[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | marathon update service: blaze-sparrow-service / wehkamp/blaze-sparrow-service:27-414d5b3
[0;39m[36m19:50:42.280[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | Deploying JObject(List((container,JObject(List((docker,JObject(List((parameters,JArray(List(JObject(List((key,JString(user)), (value,JString(498:498)))), JObject(List((key,JString(log-opt)), (value,JString(tag=docker.blaze-sparrow-service)))), JObject(List((key,JString(log-driver)), (value,JString(fluentd)))), JObject(List((key,JString(label)), (value,JString(role=sparrow)))), JObject(List((key,JString(label)), (value,JString(team=Checkout)))), JObject(List((key,JString(log-opt)), (value,JString(labels=team))))))), (image,JString(wehkamp/blaze-sparrow-service:27-414d5b3)), (portMappings,JArray(List(JObject(List((containerPort,JInt(5000)), (hostPort,JInt(0)), (protocol,JString(tcp))))))), (privileged,JBool(true)), (network,JString(BRIDGE))))), (type,JString(DOCKER))))), (healthChecks,JArray(List(JObject(List((timeoutSeconds,JInt(10)), (path,JString(/status)), (portIndex,JInt(0)), (gracePeriodSeconds,JInt(30)), (maxConsecutiveFailures,JInt(3)), (intervalSeconds,JInt(60)), (protocol,JString(HTTP))))))), (labels,JObject(List((io.vamp.deployment,JString(blaze-sparrow-service)), (io.vamp.cluster,JString(blaze-sparrow-service)), (io.vamp.service,JString(blaze-sparrow-service:27-414d5b3))))), (uris,JArray(List(JString(file:///etc/.dockercfg)))), (id,JString(/govamp/deployment-blaze-sparrow-service-service-36f623682f06ebaca1dddd55b8b0066e4bd9d926)), (instances,JInt(1)), (cpus,JDouble(0.1)), (mem,JInt(500)), (env,JObject(List((LOG_JSON_TCP_HOST,JString(logging.blaze:5170)), (SERVICE_NAME,JString(blaze-sparrow-service)), (SERVICE_TAGS,JString(vamp-managed))))), (constraints,JArray(List()))))
[0;39m[36m19:50:52.273[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | marathon update service: blaze-sparrow-service / wehkamp/blaze-sparrow-service:27-414d5b3
[0;39m[36m19:50:52.274[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | Deploying JObject(List((container,JObject(List((docker,JObject(List((parameters,JArray(List(JObject(List((key,JString(user)), (value,JString(498:498)))), JObject(List((key,JString(log-opt)), (value,JString(tag=docker.blaze-sparrow-service)))), JObject(List((key,JString(log-driver)), (value,JString(fluentd)))), JObject(List((key,JString(label)), (value,JString(role=sparrow)))), JObject(List((key,JString(label)), (value,JString(team=Checkout)))), JObject(List((key,JString(log-opt)), (value,JString(labels=team))))))), (image,JString(wehkamp/blaze-sparrow-service:27-414d5b3)), (portMappings,JArray(List(JObject(List((containerPort,JInt(5000)), (hostPort,JInt(0)), (protocol,JString(tcp))))))), (privileged,JBool(true)), (network,JString(BRIDGE))))), (type,JString(DOCKER))))), (healthChecks,JArray(List(JObject(List((timeoutSeconds,JInt(10)), (path,JString(/status)), (portIndex,JInt(0)), (gracePeriodSeconds,JInt(30)), (maxConsecutiveFailures,JInt(3)), (intervalSeconds,JInt(60)), (protocol,JString(HTTP))))))), (labels,JObject(List((io.vamp.deployment,JString(blaze-sparrow-service)), (io.vamp.cluster,JString(blaze-sparrow-service)), (io.vamp.service,JString(blaze-sparrow-service:27-414d5b3))))), (uris,JArray(List(JString(file:///etc/.dockercfg)))), (id,JString(/govamp/deployment-blaze-sparrow-service-service-36f623682f06ebaca1dddd55b8b0066e4bd9d926)), (instances,JInt(1)), (cpus,JDouble(0.1)), (mem,JInt(500)), (env,JObject(List((LOG_JSON_TCP_HOST,JString(logging.blaze:5170)), (SERVICE_NAME,JString(blaze-sparrow-service)), (SERVICE_TAGS,JString(vamp-managed))))), (constraints,JArray(List()))))
[0;39m[36m19:51:02.273[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | marathon update service: blaze-sparrow-service / wehkamp/blaze-sparrow-service:27-414d5b3
[0;39m[36m19:51:02.275[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | Deploying JObject(List((container,JObject(List((docker,JObject(List((parameters,JArray(List(JObject(List((key,JString(user)), (value,JString(498:498)))), JObject(List((key,JString(log-opt)), (value,JString(tag=docker.blaze-sparrow-service)))), JObject(List((key,JString(log-driver)), (value,JString(fluentd)))), JObject(List((key,JString(label)), (value,JString(role=sparrow)))), JObject(List((key,JString(label)), (value,JString(team=Checkout)))), JObject(List((key,JString(log-opt)), (value,JString(labels=team))))))), (image,JString(wehkamp/blaze-sparrow-service:27-414d5b3)), (portMappings,JArray(List(JObject(List((containerPort,JInt(5000)), (hostPort,JInt(0)), (protocol,JString(tcp))))))), (privileged,JBool(true)), (network,JString(BRIDGE))))), (type,JString(DOCKER))))), (healthChecks,JArray(List(JObject(List((timeoutSeconds,JInt(10)), (path,JString(/status)), (portIndex,JInt(0)), (gracePeriodSeconds,JInt(30)), (maxConsecutiveFailures,JInt(3)), (intervalSeconds,JInt(60)), (protocol,JString(HTTP))))))), (labels,JObject(List((io.vamp.deployment,JString(blaze-sparrow-service)), (io.vamp.cluster,JString(blaze-sparrow-service)), (io.vamp.service,JString(blaze-sparrow-service:27-414d5b3))))), (uris,JArray(List(JString(file:///etc/.dockercfg)))), (id,JString(/govamp/deployment-blaze-sparrow-service-service-36f623682f06ebaca1dddd55b8b0066e4bd9d926)), (instances,JInt(1)), (cpus,JDouble(0.1)), (mem,JInt(500)), (env,JObject(List((LOG_JSON_TCP_HOST,JString(logging.blaze:5170)), (SERVICE_NAME,JString(blaze-sparrow-service)), (SERVICE_TAGS,JString(vamp-managed))))), (constraints,JArray(List()))))
[0;39m[36m19:51:12.276[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | marathon update service: blaze-sparrow-service / wehkamp/blaze-sparrow-service:27-414d5b3
[0;39m[36m19:51:12.276[0;39m [34m| INFO  | i.v.c.marathon.MarathonDriverActor       | amp/user/govamp/marathon-driver-actor-23 | Deploying JObject(List((container,JObject(List((docker,JObject(List((parameters,JArray(List(JObject(List((key,JString(user)), (value,JString(498:498)))), JObject(List((key,JString(log-opt)), (value,JString(tag=docker.blaze-sparrow-service)))), JObject(List((key,JString(log-driver)), (value,JString(fluentd)))), JObject(List((key,JString(label)), (value,JString(role=sparrow)))), JObject(List((key,JString(label)), (value,JString(team=Checkout)))), JObject(List((key,JString(log-opt)), (value,JString(labels=team))))))), (image,JString(wehkamp/blaze-sparrow-service:27-414d5b3)), (portMappings,JArray(List(JObject(List((containerPort,JInt(5000)), (hostPort,JInt(0)), (protocol,JString(tcp))))))), (privileged,JBool(true)), (network,JString(BRIDGE))))), (type,JString(DOCKER))))), (healthChecks,JArray(List(JObject(List((timeoutSeconds,JInt(10)), (path,JString(/status)), (portIndex,JInt(0)), (gracePeriodSeconds,JInt(30)), (maxConsecutiveFailures,JInt(3)), (intervalSeconds,JInt(60)), (protocol,JString(HTTP))))))), (labels,JObject(List((io.vamp.deployment,JString(blaze-sparrow-service)), (io.vamp.cluster,JString(blaze-sparrow-service)), (io.vamp.service,JString(blaze-sparrow-service:27-414d5b3))))), (uris,JArray(List(JString(file:///etc/.dockercfg)))), (id,JString(/govamp/deployment-blaze-sparrow-service-service-36f623682f06ebaca1dddd55b8b0066e4bd9d926)), (instances,JInt(1)), (cpus,JDouble(0.1)), (mem,JInt(500)), (env,JObject(List((LOG_JSON_TCP_HOST,JString(logging.blaze:5170)), (SERVICE_NAME,JString(blaze-sparrow-service)), (SERVICE_TAGS,JString(vamp-managed))))), (constraints,JArray(List()))))
```

And just the following final line regarding the container:

```
[0;39m[36m19:51:22.416[0;39m [1;31m| ERROR | io.vamp.common.notification.Notification |                                          | Deployment service error for deployment 'blaze-sparrow-service' and service 'blaze-sparrow-service:27-414d5b3'.
```

@bench87 having any luck in reproducing?

**Comment by harmw** [comment]
Am I right in my understanding that the `health`-workflow is responsible for communication between Vamp and the orchestration engine (in our scenario Marathon/Mesos) and as such is the component to manage this? (eg. putting things on _healthy/unhealthy_)

**Comment by olafmol** [comment]
Health workflow is run the "health" node.JS script (stored in the health breed artifact), it only generates a "health" metric type to the event API so the UI can display this. Health workflow is thus not influencing anything in the scheduler engines, it's read-only.

**Comment by bench87** [comment]
it is reproducing other app and then the other app,

my event log is blow
event | elasticsearch_pulse:ERROR info | HttpClientException

**Comment by bench87** [comment]
@olafmol 
my new issued app blueprint

``` 
name: nginx-blueprint
kind: blueprint
metadata: {}
gateways: {}
clusters:
  nginx:
    metadata: {}
    services:
    - breed:
        name: nginx-a:1.0.0
        kind: breed
        metadata: {}
        deployable:
          definition: nginx:1.13.9
        ports:
          webport: 80/http
        environment_variables: {}
        constants: {}
        arguments: []
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 32.00MB
        instances: 1
      arguments:
      - privileged: 'true'
      health_checks:
      - path: /
        port: webport
        initial_delay: 10s
        timeout: 5s
        interval: 10s
        failures: 10
        protocol: HTTP
      dialects: {}
      health:
        staged: 0
        running: 1
        healthy: 1
        unhealthy: 0
    - breed:
        name: nginx-b:1.0.0
        kind: breed
        metadata: {}
        deployable:
          definition: nginx:1.13.9
        ports:
          webport: 80/http
        environment_variables: {}
        constants: {}
        arguments: []
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 32.00MB
        instances: 1
      arguments:
      - privileged: 'true'
      health_checks:
      - path: /
        port: webport
        initial_delay: 10s
        timeout: 5s
        interval: 10s
        failures: 10
        protocol: HTTP
      dialects: {}
      health:
        staged: 0
        running: 1
        healthy: 1
        unhealthy: 0
    gateways:
      webport:
        sticky: null
        virtual_hosts:
        - webport.nginx.nginx-a.vamp
        - vamp.nginx.dev.toss.bz
        routes:
          nginx-b:1.0.0:
            lookup_name: 34e2933d9f1189fc3a301cfcc01e19d956b8dec7
            weight: 48%
            balance: default
            condition:
              condition: hdr(X-Real-IP) -m ip 192.168.201.122
            condition_strength: 100%
            rewrites: []
          nginx-a:1.0.0:
            lookup_name: 44a00980d450a4e9f026dafef48d83bd13f19dde
            weight: 52%
            balance: default
            condition:
              condition: hdr(X-Real-IP) -m ip 192.168.201.121
            condition_strength: 100%
            rewrites: []
    dialects: {}
environment_variables: {}
dialects: {}

```
