### ISSUE TITLE
initial weight value issue

### ISSUE THREAD

**Issue by bench87** [magneticio/vamp#1109]
@olafmol Im so sorry for a lot of questions

I deployed toss-app with router weight 100% and then I deployed toss-app version2 like blow
I want version2 router weight 0% but when I merged version2 into toss-app router become 50% 50%...
vamp:0.5.5 initial weight is 0% but vamp:0.5.5.6 is not
how can I do merge with weight 0%

```
name: toss-app:1.13.56-api-refactoring-dev
kind: blueprint
metadata: {}
gateways: {}
clusters:
  dev:
    metadata: {}
    services:
    - breed:
        name: toss-app:1.13.56-api-refactoring-dev
        kind: breed
        metadata: {}
        deployable:
          definition: docker.toss.bz/toss-app:1.13.56-api-refactoring-dev
        ports:
          webport: 21322/http
        environment_variables:
          JVM_OPT: -Xms512m -Xmx512m -XX:NewSize=128m
          PROFILE: dev
        constants: {}
        arguments: []
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 512.00MB
        instances: 1
      arguments:
      - privileged: 'true'
      health_checks:
      - path: /health
        port: webport
        initial_delay: 10s
        timeout: 10s
        interval: 10s
        failures: 0
        protocol: HTTP
      dialects:
        marathon:
          container:
            volumes:
            - containerPath: /toss/log/toss-app-server/threaddump
              hostPath: /data0/java/threaddump
              mode: RW
      health:
        staged: 0
        running: 1
        healthy: 1
        unhealthy: 0
    gateways:
      webport:
        sticky: null
        virtual_hosts:
        - vamp.app.dev.toss.bz
        routes:
          toss-app:1.13.56-api-refactoring-dev:
            lookup_name: 819e1c79b811dac29d54ab190cbdc8cb4fcafb34
            weight: "0%"
            balance: default
            condition:
              condition: hdr(X-Real-IP) -m ip 192.168.23.51
            condition_strength: 100%
            rewrites: []
    dialects: {}
environment_variables: {}
dialects: {}
```
