### ISSUE TITLE
I want to know marathon constraints syntax

### ISSUE THREAD

**Issue by bench87** [magneticio/vamp#1110]
I want to put constraits hostname: UNIQUE to marathon
I have inserted dialects  but not working

my blueprint blow:
```
name: core:0.6.2-master-staging
kind: blueprint
metadata: {}
gateways: {}
clusters:
  staging:
    metadata: {}
    services:
    - breed:
        name: core:0.6.2-master-staging
        kind: breed
        metadata: {}
        deployable:
          definition: docker.toss.bz/core:0.6.2-master
        ports:
          webport: 12000/http
        environment_variables:
          JVM_OPT: -Xms512m -Xmx512m
          PROFILE: staging
        constants: {}
        arguments: []
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 1024.00MB
        instances: 1
      arguments:
      - privileged: 'true'
      health_checks:
      - path: /health
        port: webport
        initial_delay: 10s
        timeout: 10s
        interval: 10s
        failures: 0
        protocol: HTTP
      dialects:
        marathon:
          container:
            volumes:
            - containerPath: /toss/log/core/threaddump
              hostPath: /data0/java/threaddump
              mode: RW
      health:
        staged: 0
        running: 1
        healthy: 1
        unhealthy: 0
    gateways:
      webport:
        sticky: null
        virtual_hosts:
        - staging.core.s.toss.bz
        routes:
          core:0.6.2-master-staging:
            lookup_name: eedf1c8f633320c3ff8e08d449669912708e5209
            weight: 0%
            balance: default
            condition: null
            condition_strength: null
            rewrites: []
    dialects:
      marathon:
        constraints:
        - 'hostname: UNIQUE'
environment_variables: {}
dialects: {}
```
