### ISSUE TITLE
Routes does not match to the Ports which are exposed 

### ISSUE THREAD

**Issue by zutherb** [magneticio/vamp#122]
Hi,

i try to get running the Vamp All-in-one with the following file (https://raw.githubusercontent.com/zutherb/AppStash/master/vamp/shop.yml) but even if in marathon all looks fine, i could not access port 9050. Unfortunately the Ports are not inject correct. When i look to the Deployments the Redis is exposed at Port 31002 but inject to the env variables is 33005. 

Here is the API-Response of the Deployment-Call: 
```
[

{

    "name": "45256ade-36ec-4a60-b4b5-20a7e2d118f2",
    "endpoints": 

{

    "catalog.port": "9050"

},
"clusters": 
{

    "cart": 

{

    "services": 

[

{

    "state": 

{

    "name": "Deployed",
    "started_at": "2015-05-25T14:37:07.267Z"

},
"breed": 
{

    "name": "cart",
    "deployable": "zutherb/cart-service",
    "ports": 

{

    "port": "18100/http"

},
"environment_variables": 
{

    "REDIS_PORT_6379_TCP_ADDR": "$redis.host",
    "REDIS_PORT_6379_TCP_PORT": "$redis.ports.port"

},
"constants": { },
"dependencies": 
{

    "redis": 

        {
            "name": "redis"
        }
    }

},
"scale": 
{

    "cpu": 0.3,
    "memory": 512,
    "instances": 1

},
"routing": 
{

    "weight": 100,
    "filters": [ ]

},
"servers": 
[

{

    "name": "45256ade-36ec-4a60-b4b5-20a7e2d118f2_cart.82e84bae-02eb-11e5-a9e8-0242ac11007d",
    "host": "192.168.53.109",
    "ports": 

        {
            "18100": 31002
        },
        "deployed": true
    }

],
"dependencies": 

        {
            "redis": "redis"
        }
    }

],
"routes": 

    {
        "18100": 33004
    }

},
"catalog": 
{

    "services": 

[

{

    "state": 

{

    "name": "Deployed",
    "started_at": "2015-05-25T14:37:20.804Z"

},
"breed": 
{

    "name": "catalog",
    "deployable": "zutherb/catalog-frontend",
    "ports": 

{

    "port": "80/http"

},
"environment_variables": 
{

    "CHECKOUT_DESIGN": "standard",
    "NAVIGATION_PORT_18090_TCP_PORT": "$navigation.ports.port",
    "PRODUCT_PORT_18080_TCP_ADDR": "$product.host",
    "PRODUCT_PORT_18080_TCP_PORT": "$product.ports.port",
    "CART_PORT_18100_TCP_ADDR": "$cart.host",
    "CART_PORT_18100_TCP_PORT": "$cart.ports.port",
    "SHOP_PORT_8080_TCP_ADDR": "$checkout.host",
    "NAVIGATION_PORT_18090_TCP_ADDR": "$navigation.host",
    "SHOP_PORT_8080_TCP_PORT": "$checkout.ports.port"

},
"constants": { },
"dependencies": 
{

    "product": 

{

    "name": "product"

},
"navigation": 
{

    "name": "navigation"

},
"cart": 
{

    "name": "cart"

},
"checkout": 

        {
            "name": "checkout"
        }
    }

},
"scale": 
{

    "cpu": 0.3,
    "memory": 512,
    "instances": 1

},
"routing": 
{

    "weight": 100,
    "filters": [ ]

},
"servers": 
[

{

    "name": "45256ade-36ec-4a60-b4b5-20a7e2d118f2_catalog.8a1748f0-02eb-11e5-a9e8-0242ac11007d",
    "host": "192.168.53.109",
    "ports": 

        {
            "80": 31004
        },
        "deployed": true
    }

],
"dependencies": 

        {
            "product": "product",
            "navigation": "navigation",
            "cart": "cart",
            "checkout": "checkout"
        }
    }

],
"routes": 

    {
        "80": 33000
    }

},
"checkout": 
{

    "services": 

[

{

    "state": 

{

    "name": "Deployed",
    "started_at": "2015-05-25T14:37:13.379Z"

},
"breed": 
{

    "name": "checkout",
    "deployable": "zutherb/monolithic-shop",
    "ports": 

{

    "port": "8080/http"

},
"environment_variables": 
{

    "CART_PORT_18100_TCP_ADDR": "$cart.host",
    "CART_PORT_18100_TCP_PORT": "$cart.ports.port",
    "MONGODB_PORT_27017_TCP_ADDR": "$mongodb.host",
    "MONGODB_PORT_27017_TCP_PORT": "$mongodb.ports.port"

},
"constants": { },
"dependencies": 
{

    "mongodb": 

{

    "name": "mongodb"

},
"cart": 

        {
            "name": "cart"
        }
    }

},
"scale": 
{

    "cpu": 0.3,
    "memory": 512,
    "instances": 1

},
"routing": 
{

    "weight": 100,
    "filters": [ ]

},
"servers": 
[

{

    "name": "45256ade-36ec-4a60-b4b5-20a7e2d118f2_checkout.868325af-02eb-11e5-a9e8-0242ac11007d",
    "host": "192.168.53.109",
    "ports": 

        {
            "8080": 31003
        },
        "deployed": true
    }

],
"dependencies": 

        {
            "mongodb": "mongodb",
            "cart": "cart"
        }
    }

],
"routes": 

    {
        "8080": 33001
    }

},
"navigation": 
{

    "services": 

[

{

    "state": 

{

    "name": "Deployed",
    "started_at": "2015-05-25T14:37:04.211Z"

},
"breed": 
{

    "name": "navigation",
    "deployable": "zutherb/navigation-service",
    "ports": 

{

    "port": "18090/http"

},
"environment_variables": 
{

    "MONGODB_PORT_27017_TCP_ADDR": "$mongodb.host",
    "MONGODB_PORT_27017_TCP_PORT": "$mongodb.ports.port"

},
"constants": { },
"dependencies": 
{

    "mongodb": 

        {
            "name": "mongodb"
        }
    }

},
"scale": 
{

    "cpu": 0.3,
    "memory": 512,
    "instances": 1

},
"routing": 
{

    "weight": 100,
    "filters": [ ]

},
"servers": 
[

{

    "name": "45256ade-36ec-4a60-b4b5-20a7e2d118f2_navigation.8121474d-02eb-11e5-a9e8-0242ac11007d",
    "host": "192.168.53.109",
    "ports": 

        {
            "18090": 31001
        },
        "deployed": true
    }

],
"dependencies": 

        {
            "mongodb": "mongodb"
        }
    }

],
"routes": 

    {
        "18090": 33003
    }

},
"redis": 
{

    "services": 

[

{

    "state": 

{

    "name": "Deployed",
    "started_at": "2015-05-25T14:36:58.357Z"

},
"breed": 
{

    "name": "redis",
    "deployable": "redis:latest",
    "ports": 

    {
        "port": "6379/tcp"
    },
    "environment_variables": { },
    "constants": { },
    "dependencies": { }

},
"scale": 
{

    "cpu": 0.3,
    "memory": 512,
    "instances": 1

},
"routing": 
{

    "weight": 100,
    "filters": [ ]

},
"servers": 
[

{

    "name": "45256ade-36ec-4a60-b4b5-20a7e2d118f2_redis.7d8b012b-02eb-11e5-a9e8-0242ac11007d",
    "host": "192.168.53.109",
    "ports": 

                {
                    "6379": 31000
                },
                "deployed": true
            }
        ],
        "dependencies": { }
    }

],
"routes": 

    {
        "6379": 33005
    }

},
"mongodb": 
{

    "services": 

[

{

    "state": 

{

    "name": "Deployed",
    "started_at": "2015-05-25T14:36:55.219Z"

},
"breed": 
{

    "name": "mongodb",
    "deployable": "mongo:latest",
    "ports": 

    {
        "port": "27017/tcp"
    },
    "environment_variables": { },
    "constants": { },
    "dependencies": { }

},
"scale": 
{

    "cpu": 0.3,
    "memory": 512,
    "instances": 1

},
"routing": 
{

    "weight": 100,
    "filters": [ ]

},
"servers": 
[

{

    "name": "45256ade-36ec-4a60-b4b5-20a7e2d118f2_mongodb.7bbf68ea-02eb-11e5-a9e8-0242ac11007d",
    "host": "192.168.53.109",
    "ports": 

                {
                    "27017": 31000
                },
                "deployed": true
            }
        ],
        "dependencies": { }
    }

],
"routes": 

    {
        "27017": 33006
    }

},
"product": 
{

    "services": 

[

{

    "state": 

{

    "name": "Deployed",
    "started_at": "2015-05-25T14:37:01.253Z"

},
"breed": 
{

    "name": "product",
    "deployable": "zutherb/product-service",
    "ports": 

{

    "port": "18080/http"

},
"environment_variables": 
{

    "MONGODB_PORT_27017_TCP_ADDR": "$mongodb.host",
    "MONGODB_PORT_27017_TCP_PORT": "$mongodb.ports.port"

},
"constants": { },
"dependencies": 
{

    "mongodb": 

        {
            "name": "mongodb"
        }
    }

},
"scale": 
{

    "cpu": 0.3,
    "memory": 512,
    "instances": 1

},
"routing": 
{

    "weight": 100,
    "filters": [ ]

},
"servers": 
[

{

    "name": "45256ade-36ec-4a60-b4b5-20a7e2d118f2_product.7f53651c-02eb-11e5-a9e8-0242ac11007d",
    "host": "192.168.53.109",
    "ports": 

        {
            "18080": 31001
        },
        "deployed": true
    }

],
"dependencies": 

        {
            "mongodb": "mongodb"
        }
    }

],
"routes": 

        {
            "18080": 33002
        }
    }

},
"ports": 
{

    "navigation.port": "33003",
    "cart.port": "33004",
    "checkout.port": "33001",
    "catalog.port": "33000",
    "mongodb.port": "33006",
    "redis.port": "33005",
    "product.port": "33002"

},
"environment_variables": 
{

    "navigation.MONGODB_PORT_27017_TCP_PORT": "33006",
    "catalog.NAVIGATION_PORT_18090_TCP_ADDR": "localhost",
    "catalog.CART_PORT_18100_TCP_PORT": "33004",
    "navigation.MONGODB_PORT_27017_TCP_ADDR": "localhost",
    "catalog.PRODUCT_PORT_18080_TCP_PORT": "33002",
    "checkout.CART_PORT_18100_TCP_PORT": "33004",
    "product.MONGODB_PORT_27017_TCP_ADDR": "localhost",
    "catalog.CART_PORT_18100_TCP_ADDR": "localhost",
    "checkout.CART_PORT_18100_TCP_ADDR": "localhost",
    "catalog.CHECKOUT_DESIGN": "standard",
    "catalog.PRODUCT_PORT_18080_TCP_ADDR": "localhost",
    "checkout.MONGODB_PORT_27017_TCP_ADDR": "localhost",
    "product.MONGODB_PORT_27017_TCP_PORT": "33006",
    "catalog.NAVIGATION_PORT_18090_TCP_PORT": "33003",
    "cart.REDIS_PORT_6379_TCP_PORT": "33005",
    "catalog.SHOP_PORT_8080_TCP_ADDR": "localhost",
    "checkout.MONGODB_PORT_27017_TCP_PORT": "33006",
    "catalog.SHOP_PORT_8080_TCP_PORT": "33001",
    "cart.REDIS_PORT_6379_TCP_ADDR": "localhost"

},
"constants": { },
"hosts": 

        {
            "checkout": "localhost",
            "catalog": "localhost",
            "cart": "localhost",
            "navigation": "localhost",
            "product": "localhost",
            "mongodb": "localhost",
            "redis": "localhost"
        }
    }

]
```

**Comment by tnolet** [comment]
Hi @zutherb, looks like a great project your working on. Let's get it working on Vamp. I looked at your blueprint and it looks fine. I deployed your blueprint to a full Marathon cluster and it work almost completely. I found a couple of things:

1. First: you are correct that the ports exposed by Marathon are not the same as you will find in your deployment. This is correct as Vamp maps these ports inside Vamp Router. The 31002 port is presumably the one you find in Marathon, whereas the 33005 is the one Vamp uses. This is correct behaviour and is how Vamp does service registry and discovery. Your services should use 33005. 

2. Your navigation service is taking its port from the env. variable "PORT".  I took a look at the code
```
int port = Integer.valueOf(Optional.fromNullable(System.getenv("PORT")).or("18090"));
```
Regretfully, this one is hijacked by Marathon and this is very, very annoying. Please see this ticket: https://github.com/mesosphere/marathon/issues/1254. Easy fix would be to use some other, name spaced variable like `NAVIGATION_PORT` and set that as a variable or constant in you breed/blueprint. Or just fix the port in a config file.

Furthermore, you are not reading the mongo port correctly yet. You are just reading the string, 
not getting it from the environment and adding it to your mongodb connection.
See: `https://github.com/zutherb/AppStash/blob/master/microservice/service/navigation/src/main/java/io/github/zutherb/appstash/shop/service/navigation/AppServer.java`

```java


    public static void main(String[] args) throws Exception {
        String mongodbHost = System.getenv(MONGODB_PORT_27017_TCP_ADDR);
        String mongodbPort = System.getenv(MONGODB_PORT_27017_TCP_PORT);

        if (isNotEmpty(mongodbHost)) {
            String mongoUri = "mongodb://" + mongodbHost + mongodbPort;
            System.setProperty("mongo.uri", mongoUri);
            LOGGER.info("Rewrite mongo.uri to " + mongoUri);
```

if fixed this in a very dirty way in this docker container `magneticio/navigation-service:latest` by just editing the bin/navigation file. This is not optimal, but you can easily fix it in your code.            

3. Your mongo service is very greedy with regards to disk space. I had trouble starting it and found this
in the logs:
```
root@custom-6212-302:/var/log/zookeeper# docker logs 8a0c1fd87d41
2015-05-25T18:30:52.880+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
2015-05-25T18:30:52.881+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
2015-05-25T18:30:52.881+0000 I JOURNAL  [initandlisten] 
2015-05-25T18:30:52.881+0000 E JOURNAL  [initandlisten] Insufficient free space for journal files
2015-05-25T18:30:52.881+0000 I JOURNAL  [initandlisten] Please make at least 3379MB available in /data/db/journal or use --smallfiles
```

It needs at least 3.4Gb of disk space to properly start. This can be an issue. I tweaked the command in the blueprint to execute `mongod` with the `--smallfiles` flag.

4. With these tweaks, I made it to the end of and order! When I was at the checkout, the "submit order" buttin submitted but then redirected `http://104.155.30.171/shop/orderconfirmation?43`. It was missing the `9050` port. When I added it manually, I got an order confirmation screen!

5. Your monolithic service runs in Tomcat and had intermittent issues with connecting to mongodb from the container. I've seen this before and is very annoying. Many times it has to do with startup times or Spring configs nog being ready. With Scala/Play/Typesafe apps this behaviour is much less.

Here's an updated blueprint with the tweaks. Hope this helps:

```yaml
---
name: shop:1.0

endpoints:
  catalog.port: 9050

clusters:

  catalog:
    services:
      breed:
        name: catalog
        deployable: zutherb/catalog-frontend
        ports:
          port: 80/http
        environment_variables:
          SHOP_PORT_8080_TCP_ADDR: $checkout.host
          SHOP_PORT_8080_TCP_PORT: $checkout.ports.port
          CHECKOUT_DESIGN: standard
          PRODUCT_PORT_18080_TCP_ADDR: $product.host
          PRODUCT_PORT_18080_TCP_PORT: $product.ports.port
          NAVIGATION_PORT_18090_TCP_ADDR: $navigation.host
          NAVIGATION_PORT_18090_TCP_PORT: $navigation.ports.port
          CART_PORT_18100_TCP_ADDR: $cart.host
          CART_PORT_18100_TCP_PORT: $cart.ports.port
        dependencies:
          product: product
          navigation: navigation
          cart: cart
          checkout: checkout

  checkout:
    services:
      breed:
        name: checkout
        deployable: zutherb/monolithic-shop
        ports:
          port: 8080/http
        environment_variables:
          CART_PORT_18100_TCP_ADDR: $cart.host
          CART_PORT_18100_TCP_PORT: $cart.ports.port
          MONGODB_PORT_27017_TCP_ADDR: $mongodb.host
          MONGODB_PORT_27017_TCP_PORT: $mongodb.ports.port
        dependencies:
          mongodb: mongodb
          cart: cart

  product:
    services:
      breed:
        name: product
        deployable: zutherb/product-service
        ports:
          port: 18080/http
        environment_variables:
          MONGODB_PORT_27017_TCP_ADDR: $mongodb.host
          MONGODB_PORT_27017_TCP_PORT: $mongodb.ports.port
        dependencies:
          mongodb: mongodb

  navigation:
    services:
      breed:
        name: navigation
        deployable: magneticio/navigation-service:latest
        ports:
          port: 18090/http
        environment_variables:
          MONGODB_PORT_27017_TCP_ADDR: $mongodb.host
          MONGODB_PORT_27017_TCP_PORT: $mongodb.ports.port          
        dependencies:
          mongodb: mongodb
      marathon:
       cmd: "export PORT=18090 && /navigation-0.6/bin/navigation"            

  cart:
    services:
      breed:
        name: cart
        deployable: zutherb/cart-service
        ports:
          port: 18100/http
        environment_variables:
          REDIS_PORT_6379_TCP_ADDR: $redis.host
          REDIS_PORT_6379_TCP_PORT: $redis.ports.port
        dependencies:
          redis: redis

  redis:
    services:
      breed:
        name: redis
        deployable: redis:latest
        ports:
          port: 6379/tcp

  mongodb:
    services:
      breed:
        name: mongodb
        deployable: mongo:latest
        ports:
          port: 27017/tcp
      marathon:
        cmd: "mongod --smallfiles"
```
