### ISSUE TITLE
Add inspect routing command

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#123]
## inspect-routing

YAML representation of a stored default routing

**Usage:** vamp inspect-routing NAME

**Example:**
```
#vamp inspect-routing canary-one
name: canary-one
  weight: 1
  filters:
  - condition: user-agent != ios
#
```
