### ISSUE TITLE
GET request for specific routings returns a 400

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#124]
Sending a GET request to the `/api/v1/routings` endpoint returns the following:
```yaml
- name: red
  weight: 10
  filters:
  - condition: user-agent != ios
  - name: my_filter_1
- name: canary-one
  weight: 1
  filters:
  - condition: user-agent != ios
```
Sending a GET request to the `/api/v1/routings/red` endpoint returns a `400 - Bad Request`

```json
{
    "message": "The request content was malformed. Unsupported request. Request: interface io.vamp.core.model.artifact.Routing"
}
```

Notice the content-type of the output is `application/json`; I've requested `application/x-yaml`.

Requesting a non-existing routing also produces this error, instead of a `404 -Not Found`

In the logfile:
```
Unsupported Persistence Request - Find - interface io.vamp.core.model.artifact.Routing
```

I'm using the Jdbc persistence.
