### ISSUE TITLE
Grouping services to one endpoint

### ISSUE THREAD

**Issue by vlesierse** [magneticio/vamp#126]
As part of my application I would like to expose two services on the same port and route them based on their paths using a `path_beg` ACL.

- http://application.com/api/a
- http://application.com/api/b

Of course I could put an API Proxy in front of the Vamp router, but it would be nicer if Vamp can support this on it's own to reduce network overhead.

```
                                    /--> Service A
Client --> API Proxy --> Vamp Router
                                    \--> Service B
```

If I'm correct the Vamp router it self can support a scenario like this already, but Vamp gives me a hard time to actually define this using a blueprint.

## Option 1
Use one cluster with multiple breeds

```  yaml
name: application
endpoints:
    service.port: 80
clusters:
    application-api:
        services:
            -   breed:
                    name: service-a
                    ports:
                        port: 8080/http
                routing:
                    filters:
                        - condition: path_beg /api/a
            -   breed:
                    name: service-b
                    ports:
                        port: 8888/http
                routing:
                    filters:
                        - condition: path_beg /api/b                
```
This options currently works without making changes to Vamp. However the weights and filters apply to all the breeds within the service which make canary releasing difficult to impossible.

How should it be possible to specify that `service-a:1.0` and `service-a:2.0` gets 50% but also `service-b:1.0` and `service-b:2.0`  

## Option 2
Grouping endpoints based on ports

```  yaml
name: application
endpoints:
    service-a.port: 80
    service-b.port: 80
clusters:
    service-a:
        services:
            breed:
                name: service-a
                ports:
                    port: 8080/http
            routing:
                filters:
                    - condition: path_beg /api/a
    service-b:
        services:
            breed:
                name: service-b
                ports:
                    port: 8080/http
            routing:
                filters:
                    - condition: path_beg /api/b
                
```
This options currently doesn't work because it will create a new port for each entry in endpoints even when the same port is specified.

Changing vamp by grouping the endpoints together using the name and port would solve this although it will still be hard to express the filter conditions to redirect the requests to a specific service.

### Option 3
Express filtering and grouping on endpoints

```  yaml
name: application
endpoints:
    application-api:
        port: 80/http
        services:
            service-a.port:
                - condition: path_beg /api/a
            service-b.port:
                - condition: path_beg /api/b
clusters:
    service-a:
        services:
            breed:
                name: service-a
                ports:
                    port: 8080/http
    service-b:
        services:
            breed:
                name: service-b
                ports:
                    port: 8888/http
```
Making it possible to describe the endpoints and specify the routing to the services underneath could enable Vamp to support this scenario.
