### ISSUE TITLE
Port & Environment Variable DSL change

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#15]
We discussed the various use cases this day and have come to the following conclusions:

# General

we split the different options for variables in general into two sets:
-   environment_variables
-  commands

This makes it instantly clear what goes where. Also, "parameters" in blueprints will be renamed to "environment_variables" already in 0.7.0-RC3.

**Case 1)** I want to "hard set" an environment variable, just like doing an `export MY_VAR=some_value` in a linux shell. I also want to be able to provide a placeholder for this in a breed, so that others might fill in the value in a blueprint when they use the breed.

**breed**

```YAML
name: my_breed
deployable: repo/container:version

environment_variables:
    MY_ENV_VAR1: some_string_value  # hard set
    MY_ENV_VAR1: ~                     # place holder, should be filled in blueprint. Use ~ to set to null value
```

**blueprint**
```YAML
name: my_blueprint

clusters:
  frontends:
    services:
    -
      breed: my_breed
    environment_variables:
        MY_ENV_VAR1:  some_string_value
        MY_ENV_VAR2:  some_other_string_value
         
```

**Case 2)** I want to resolve a reference and set it as the value for an environment variable. This reference can either be dynamically resolved at deploy-time, like ports and hosts names we don't know till a deployment is done, or be a reference to a hardcoded and published constant from some other part of the blueprint or breed, typically a dependency.

I would use this to hook up services at runtime based on host/port combinations or to use a hard dependency that never changes but should be provided by another breed.

```YAML
name: my_blueprint

clusters:

  frontend:
    breed:
      name: my_breed
    environment_variables:
        MY_ENV_VAR1: $backend.host        # resolves to the dynamically assigned host
        MY_ENV_VAR2: $backend.ports.port  # resolves to the dynamically assigned port
        MY_ENV_VAR3: $backend.constants.important_thing  # resolves to the "published" constant value
      dependencies:
        backend: my_other_breed
  backend:
    breed:
      name: my_other_breed
    constants:
      important_thing: some_value   
```
# Response from deployment

The deployment endpoint will return the environment variables in a separate JSON object from the resolved hostnames. This is different than before and makes sense because the hosts are separate entities and not really environment variables. Example:

```JSON
{
  "environment_variables": {
  "mysql.environment_variables.password": "secret",
  "mysql.ports.port": 33000,
  "wordpress.ports.port": 33001
},
  "hosts" : {
    "mysql.host": "10.210.110.57",
    "wordpress.host": "10.210.110.57",
  }
}
```
