### ISSUE TITLE
If scale instances is greater than 1, services can't be deployed using Docker driver

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#159]

**Comment by dragoslav** [comment]
It stays in ReadyForDeployment state:

```
name: sava:1.0

endpoints:
  sava.port: 9050

clusters:

  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 80/http
    
      scale:
          cpu: 1
          memory: 1024
          instances: 2
```
