### ISSUE TITLE
Log4j Class not found on running CLI

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#161]
```
ims-MacBook-Pro:vamp-core tim$ export VAMP_HOST=http://10.245.9.97:8080
Tims-MacBook-Pro:vamp-core tim$ java -jar /Users/tim/IdeaProjects/vamp-core/cli/target/scala-2.11/vamp-cli-0.7.6.9b23fc8.jar info
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
message: Hi, I'm Vamp! How are you?
jvm:
  operating_system:
    name: Linux
    architecture: amd64
    version: 3.16.0-0.bpo.4-amd64
    available_processors: 2.0
    system_load_average: 0.0
  runtime:
    process: 5447@vamp-scala-days.c.nomadic-thinker-642.internal
    virtual_machine_name: Java HotSpot(TM) 64-Bit Server VM
    virtual_machine_vendor: Oracle Corporation
    virtual_machine_version: 25.45-b02
    start_time: 1433418293582
```
