### ISSUE TITLE
Vamp API Gateway

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#167]
# Vamp API Gateway / TLDR

Vamp should support the basic functionality of an API gateway more completely and separately from any inter-service routing already in place. This feature proposal is based based on https://github.com/magneticio/vamp/issues/126 and general feedback and patterns found in the community. 

This means **endpoints** should be separate and independently deployable and configurable artefacts, that *can* be part of a breed or blueprint, but don't have to. Similar to scales, filters or other nested resources.

Multiple endpoints make the gateway. One gateway maps to one running HAProxy setup or a cluster of HAproxies.

## Rationale

We need this feature because:

## Features

It should do

## Implementation direction

Any references to a endpoints only exist in blueprints and deployments.

Example blueprint DSL

```YAML
name: my_blueprint
gateway:
endpoints:
    application-api:
        port: 80/http
        services:
            service-a.port:
                - condition: path_beg /api/a
            service-b.port:
                - condition: path_beg /api/b
clusters:
    service-a:
        services:
            breed:
                name: service-a
                ports:
                    port: 8080/http
    service-b:
        services:
            breed:
                name: service-b
                ports:
                    port: 8888/http
```
We could build this in the following way.

## References

http://microservices.io/patterns/apigateway.html
http://techblog.netflix.com/2013/01/optimizing-netflix-api.html
http://nginx.com/blog/building-microservices-using-an-api-gateway/

**Comment by dragoslav** [comment]
Referencing endpoints:

```YAML
endpoints:
  # another top level gateway
  $gateway:
    - condition: ... # anonymous filter, it can be by name, e.g. filter: android
  # deployment gateway
  $deployment/$gateway:
    - condition: ...
  # cluster port of a deployment
  $deployment/$cluster/$port:
    - condition: ...
  # service port of deployment/cluster
  $deployment/$cluster/$service/$port
    - condition: ...

```

For gateways defined in a blueprint (deployment) reference to deployment's gateway or cluster is implicit (current deployment).
