### ISSUE TITLE
Allow Vamp to deploy JARs/ZIPs to Marathon

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#170]
We want to allow users to use the ability of Marathon to deploy jar-files and/or zip-files.
We have to allow this in the breed DSL and in update the container driver.
Example DSL would be:
`deployable: docker://magneticio/monarch:0.1`
or 
`deployable: jar://some_location_of_a_jar_file.jar`

**Comment by dragoslav** [comment]
Solution with schema:
deployable: schema://definition

Docker driver only support 'docker' schema.
Marathon driver supports 'docker', 'cmd' & 'command' (alias).

In case that additional jars, zips... are required, Marathon dialects can be used:
```YAML
name: cool-script

clusters:
  cool:
    services:
      breed:
        name: cool-script
        deployable: cmd://app/cool-script.sh

      marathon:
        uris:
        - https://example.com/app.zip
```
