### ISSUE TITLE
Create REST API for workflows: scripts and their scheduling

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#179]
#168 

/api/v1/workflows
/api/v1/scheduled-workflows

**Comment by dragoslav** [comment]
Added:
- REST API (CRUD)
- Workflow and ScheduledWorkflow YAML readers
- In-memory and Elasticsearch persistence support
- Workflow serialization

DSL examples:

```YAML
# workflow
name: logger
script: |

  vamp.log("hi")

# scheduled workflow
name: scheduled-logger
workflow: logger # workflow reference
# time trigger
time: 15 9 5 1 
# deployment trigger
deployment: deployment/cluster?create|update|delete 
# event trigger
tags:
- deployment
- cluster

# embedded script, only if workflow is not specified
script: vamp.log()

# note: only one trigger can be defined, priority (from highest):
# - deployment
# - time
# - event (tag) based

```
