### ISSUE TITLE
Support interpolation of parameters which are defined in the dialect section

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#182]
Problem - breed can't contain all information about deployment.
Example:

```YAML
# defined in the breed
deployable: cmd://./run.sh

# defined in the blueprint
dialects:
  marathon:
    uris:
    - http://.../app.zip # Marathon will unzip the archive, then it will call the run.sh
```

Solution would be:

```YAML
# breed
deployable: cmd://./run.sh
constants:
  artifact: app.zip

# blueprint
dialects:
  marathon:
    uris:
    - http://.../$artifact # it could be also the full URL
```

**Comment by dragoslav** [comment]
```YAML
name: sava:1.0
endpoints:
  sava.port: 9050
clusters:
  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 80/http
        constants:
          jar: sava-1.0.jar
    marathon:
      env:
        LD_LIBRARY_PATH: /usr/local/lib/myLib # no interpolation
        TAR: $$tar  # escaped by $
        ZIP: $zip   # doesn't exist
        JAR: $jar   # local scope
        GLOBAL_JAR: $sava.constants.jar # global scope

```

will lead to "env":

```JavaScript
  LD_LIBRARY_PATH=/usr/local/lib/myLib
  ZIP=
  TAR=$tar
  GLOBAL_JAR=sava-1.0.jar
  JAR=sava-1.0.jar
```
