### ISSUE TITLE
Implement time based triggers for workflows

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#189]
related to #168

**Comment by dragoslav** [comment]
Including Cron (Quartz) pattern and basic logging  support:

```YAML
name: logger-schedule
# every 3 seconds
time: "*/3 * * * * ?"
# log an error using "logger-schedule" as logger name (name of this artifact)
script: vamp.error('alert')
```
