### ISSUE TITLE
Implement deployment (create, update, delete) based triggers for workflows

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#190]
#168

**Comment by dragoslav** [comment]
```YAML
name: logger-schedule
deployment: 9e67a7eb-cb64-45f5-b619-fbad179afe5a

script: vamp.error('deployment change...')
```

is equivalent to:

```YAML
name: logger-schedule
tags: 
- deployments
- deployments:9e67a7eb-cb64-45f5-b619-fbad179afe5a

script: vamp.error('deployment change...')
```

This is starting point for more generic trigger:
create/update/delete on deployment/cluster/service
For this we need first #201

Example for monitoring cluster changes:

```YAML
name: logger-schedule
deployment: 9e67a7eb-cb64-45f5-b619-fbad179afe5a/sava?create&update&delete

script: vamp.error('cluster change...')
```
