### ISSUE TITLE
Implement generic event (tag) based triggers for workflows

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#191]
#168

**Comment by dragoslav** [comment]
```YAML
name: logger-schedule
tags:
- breeds

script: vamp.info('breed event!!!')

```
