### ISSUE TITLE
Support for workflow local storage

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#195]
#168 
It should be possible to store and retrieve data (JSON) between workflow execution.

```JavaScript

var counter = storage.get("counter")
if(!counter) 
  storage.put("counter", counter = 0)
else 
  storage.put("counter", ++counter)

vamp.info(counter) // successive execution: 0, 1, 2, ...

```

**Comment by dragoslav** [comment]
```YAML
name: counter-schedule
time: "*/3 * * * * ?"

script: |
  var counter = storage.get("counter")
  if(!counter) counter = 0
  log.info(counter)
  storage.put("counter", ++counter)
```

Or it can be pre-initialised:

```YAML
name: counter-schedule
time: "*/3 * * * * ?"
storage:
  counter: 0

script: |
  var counter = storage.get("counter")
  log.info(counter)
  storage.put("counter", ++counter)
```
