### ISSUE TITLE
Import additional scripts

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#198]
#168 
For instance from another workflow or external (e.g. underscore.js)

**Comment by dragoslav** [comment]
Importing internal (workflow) and external JavaScript sources. Example:

1) create a workflow (/api/v1/workflows), adding a "log" function
```YAML
name: vamp-common.js
script: function log(msg) { vamp.info(msg); }
```
2) schedule a workflow (/api/v1/scheduled-workflows)
```YAML
name: logger-schedule
time: "*/3 * * * * ?" # every 3 seconds
import:
- http://underscorejs.org/underscore-min.js # external
- vamp-common.js # internal

script: _.each([1, 2, 3], function(num){ log(num); }); 
```

External scripts will be loaded before each execution. 
One way to avoid that is to create a workflow with content of the script and use it as an internal workflow reference.
