### ISSUE TITLE
Add more states and events to Deployment synchronization

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#201]
We have: ReadyForDeployment, Deployed, ReadyForUndeployment
It would be more useful for UI to have more specific states related to Marathon/Docker deployment, router setup etc. Internally we could keep existing logic.
Also, we should crete CREATE/UPDATE/DELETE events on cluster/service level.
So if a new service (e.g. A/B testing) is deployed we should be able to react on the change (e.g. executing a workflow).

optional features:
- Storing the more granular events as "archive events" to Pulse
- Adding some sort of status code for the various possible statuses instead of the string. This number should give an indication of where you are the deployment process, i.e. status 100 is earlier than 900.

**Comment by dragoslav** [comment]
Intention: Deploy & Undeploy, each of them:
- Initiated
- ContainerUpdate
- RouteUpdate
- Done

```yaml
- state:
    intention: Deploy
    since: '2015-09-20T22:07:50.456+02:00'
    step:
      name: ContainerUpdate
      since: '2015-09-20T22:07:52.131+02:00'
```
