### ISSUE TITLE
Docker driver doesn't pass the full array of environment variables.

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#202]
It seems to only pass the last entry in the map. When I provide the following blueprint:

```yaml
name: monarchs:1.0
endpoints:
  frontend.port: 9050
clusters:
  frontend:
    services:
      -
        breed:
          name: monarch_front:0.1
          deployable: magneticio/monarch:0.1
          ports:
            port: 8080/http
          environment_variables:
           MONARCH_DEPENDS_ON_HOST: some_host
           MONARCH_DEPENDS_ON_PORT: 12345
```
only the last one ends up in the Docker containers' environment, i.e.:

```
        "Env": [
            "MONARCH_DEPENDS_ON_PORT=12345",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
```
