### ISSUE TITLE
Add "requires" field in workflows

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#207]
Part of validation, example workflow:

```YAML
name: ...

requires:
- deployment
- cluster

script: ...
```

"requires" are expected storage entries set in scheduled workflow definition.

**Comment by dragoslav** [comment]
Workflow:

```YAML
name: logger
requires: # it could be shortened to: 'requires: message'
  - message
script: log.info(storage.get("message"))
```

Scheduled workflow:

```YAML
name: scheduled-workflow
workflow: logger
time: "*/3 * * * * ?"

storage:
  message: hi # without this an error will be reported
```
