### ISSUE TITLE
Support setting objects in scheduled workflow storage

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#208]
```YAML
name: ...
storage:
  deployment: deployments/de305d54-75b4-431b-adb2-eb6b9e546014
  cluster: deployments/de305d54-75b4-431b-adb2-eb6b9e546014/clusters/sava
```

"deployment" and "cluster" will be resolved to object values before script evaluation.
