### ISSUE TITLE
Parameter --stdin does not work

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#218]
Test the newly added --stdin parameter

**Comment by plamola** [comment]
Create an input file, saved as breed.yaml:
```yaml
name: monarch-4
deployable: magneticio/monarch:latest-4
ports:
  name: port
  value: 8080/http    
dependencies:
  db: mysql
environment_variables: 
  TEST: my little environment setting
constants:
  username: SA 
```

Tested the following command:
```vamp generate breed --stdin --name test_stdin --deployable test_container < breed.yaml ```

Vamp is being told to read the file from stdin by the parameter `--stdin`.
The content of the `breed.yaml` file is redirected to stdin.


In the output, the file content is merged with the additional parameters `--name` and `--deployable`:
```yaml
name: test_stdin
deployable: docker://test_container
ports:
  name: port
  value: 8080/http
environment_variables:
  TEST: my little environment setting
constants:
  username: SA
dependencies:
  db:
    name: mysql
```

Guess the `--stdin` parameter is working as expected.
