### ISSUE TITLE
Marathon dialects tags are not persisted anymore!

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#219]
This example is not working anymore. Storing this blueprint returns empty dialects tags

```yaml
name: busy-top:1.0

clusters:

  busyboxes:
    services:
      breed:
        name: busybox
        deployable: registry.magnetic.io/busybox:latest
      marathon:
       cmd: "top"      
       uris:
         -
           "https://some_host/some_path/some_file_with_docker_credentials"
       labels:
         environment: "staging"
         owner: "buffy the vamp slayer"
       container:  
         volumes:
           -
             containerPath: "/tmp/"
             hostPath: "/tmp/"
             mode: "RW"
      scale:
        cpu: 0.1       
        memory: 256  
        instances: 1
```
