### ISSUE TITLE
Add an "include" tag/option to the DSL & CLI for easily cloning or extending existing blueprints and breeds

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#232]
# Add "include" tag

In common use cases where a lot of canary releases and deployments are done of very similar artefacts, we require the user to essentially duplicate a lot of settings in blueprints and breeds. This is just a requirement of Vamp's underlying model where each breed and blueprint should be a complete artefact. This model is fine, but we should create a usability feature where you can include all the settings of an existing artefact in a blueprint/breed and just change a couple of settings, like the deployable.

## Rationale

- easy canary releasing and iterating on very similar artefacts.
- makes scripting with the CLI easier.
- less implicit duplication when forging blueprints by hand.

## YAML Example

An existing breed:

```yaml
name: monarch_front:0.1
deployable: docker://magneticio/monarch:0.1
ports:
  port: 8080/http
environment_variables:
  MONARCH_DEPENDS_ON_HOST: $backend.host
  MONARCH_DEPENDS_ON_PORT: $backend.ports.jdbc
constants: {}
dependencies:
  backend:
    name: monarch_backend:0.2
```

and then the new breed based on the former. 

```yaml
name: monarch_front:0.2
deployable: docker://magneticio/monarch:0.2
include: monarch_front:0.1
```

Note: this is the way the breed is submitted to the API. This is the way it is stored.
The reference is expanded and checked at deploy time.

## CLI Example

instead of using user provided templates to create breeds, you can use the `--include` option to specify  breed you want to "inherit", i.e:
```bash
vamp create breed monarch:0.2 --deployable=magneticio/monarch:0.2 --include monarch:0.1
```
this command would use the monarch:0.1 breed as "base" and just set a new name and deployable.
