### ISSUE TITLE
Get expanded artifact

### ISSUE THREAD

**Issue by plamola** [magneticio/vamp#24]
Retrieve artifacts with all dependencies resolved. 
In essence, return the complete sub tree of the artifact.

If resolving one of the referenced artifacts fails, an error is thrown, specifying the name and type of the missing artifact.

This can be implemented as a layer on top of the current persistence implementation, using the result of the 'Get artifact(s)' call and traverse the artifact sub-tree, replacing all references found.

magneticio/vamp-internal#209

**Comment by dragoslav** [comment]
expand_references=true

```YAML
http://localhost:8080/api/v1/breeds/monarch

name: monarch
deployable: docker://magneticio/monarch:latest
ports: {}
environment_variables: {}
constants: {}
dependencies:
  db: mysql
```
```YAML
http://localhost:8080/api/v1/breeds/monarch?expand_references=true

name: monarch
deployable: docker://magneticio/monarch:latest
ports: {}
environment_variables: {}
constants: {}
dependencies:
  db:
    name: mysql
    deployable: docker://mysql
    ports: {}
    environment_variables: {}
    constants: {}
    dependencies: {}
```
