### ISSUE TITLE
Resource Allocation in marathon is not the same like defined in the blueprint

### ISSUE THREAD

**Issue by zutherb** [magneticio/vamp#247]
Hi,

i try to setup an a/b test for my online shop example (https://github.com/zutherb/AppStash/blob/master/vamp/shop.yml). User should get a green version of the layout when they are using the Chrome browser.

It seems that the ressource allocation by marathon is not done like i have defined in the blueprint:

```yaml
          scale:
            instances: 1
            cpu: 0.1
            memory: 128
```

When i am look to marathon 513MB and 0.3 CPU is used: 

<img width="1440" alt="bildschirmfoto 2015-07-05 um 10 15 13" src="https://cloud.githubusercontent.com/assets/489474/8510920/f7b1b826-22ff-11e5-91b5-147a010f0043.png">

Furthermore both a/b test container are initialized with the environment variables ```CHECKOUT_DESIGN=amelia```. But the standard container should have:
```yaml
 environment_variables:
            CHECKOUT_DESIGN: standard
```
<img width="1440" alt="bildschirmfoto 2015-07-05 um 10 23 09" src="https://cloud.githubusercontent.com/assets/489474/8510921/fa8ca538-22ff-11e5-957e-127dd0ef15c8.png">

<img width="1435" alt="bildschirmfoto 2015-07-05 um 10 22 45" src="https://cloud.githubusercontent.com/assets/489474/8510922/fabb1c2e-22ff-11e5-91f9-d13f930a2d46.png">

I am using:
Marathon 0.8.2
Vamp 0.7.7

**Comment by olafmol** [comment]
Hi Bernd, thanks for reporting, investigating this issue now.

**Comment by plamola** [comment]
@zutherb Any chance you are using docker version 1.7?

In Docker 1.7 (released 2015-06-16), the settings for cpu and memory have been moved to a different section in the API. I suspect that Marathon 0.8.2 (released 2015-06-04) won't be aware of these settings being moved.

If in fact you are using Docker 1.7, downgrading to Docker 1.6 might resolve the cpu & memory issue.

For the incorrect set environment variable, I'll have to get back to you at a later time.

**Comment by zutherb** [comment]
@plamola i tried out Docker 1.6 and 1.7 on both version i has the behaviour. I hope marathon 0.9.0 will fix it.

**Comment by zutherb** [comment]
Hi @plamola i updated to marathon 0.9.0 now. The resource allocation seems to be pebkac problem
The error was in the breed declaration:
```yaml
  catalog:
    services:
      -
        breed:
          name: catalog:a
          deployable: zutherb/catalog-frontend:latest
          ports:
            port: 80/http
          environment_variables:
            CHECKOUT_DESIGN: standard
            SHOP_PORT_8080_TCP_ADDR: $checkout.host
            SHOP_PORT_8080_TCP_PORT: $checkout.ports.port
            PRODUCT_PORT_18080_TCP_ADDR: $product.host
            PRODUCT_PORT_18080_TCP_PORT: $product.ports.port
            NAVIGATION_PORT_18090_TCP_ADDR: $navigation.host
            NAVIGATION_PORT_18090_TCP_PORT: $navigation.ports.port
            CART_PORT_18100_TCP_ADDR: $cart.host
            CART_PORT_18100_TCP_PORT: $cart.ports.port
          dependencies:
            product: product
            navigation: navigation
            cart: cart
            checkout: checkout
          scale:
            instances: 1
            cpu: 0.1
            memory: 128
          routing:
            weight: 100
      -
        breed:
          name: catalog:b
          deployable: zutherb/catalog-frontend:latest
          ports:
            port: 80/http
          environment_variables:
            CHECKOUT_DESIGN: amelia
            SHOP_PORT_8080_TCP_ADDR: $checkout.host
            SHOP_PORT_8080_TCP_PORT: $checkout.ports.port
            PRODUCT_PORT_18080_TCP_ADDR: $product.host
            PRODUCT_PORT_18080_TCP_PORT: $product.ports.port
            NAVIGATION_PORT_18090_TCP_ADDR: $navigation.host
            NAVIGATION_PORT_18090_TCP_PORT: $navigation.ports.port
            CART_PORT_18100_TCP_ADDR: $cart.host
            CART_PORT_18100_TCP_PORT: $cart.ports.port
          dependencies:
            product: product
            navigation: navigation
            cart: cart
            checkout: checkout
          scale:
            instances: 1
            cpu: 0.1
            memory: 128
           routing:
             weight: 0
             filters:
               - condition: User-Agent = Chrome
```
But the indentings must be:
```yaml
  catalog:
    services:
      -
        breed:
          name: catalog:a
          deployable: zutherb/catalog-frontend:latest
          ports:
            port: 80/http
          environment_variables:
            CHECKOUT_DESIGN: standard
            SHOP_PORT_8080_TCP_ADDR: $checkout.host
            SHOP_PORT_8080_TCP_PORT: $checkout.ports.port
            PRODUCT_PORT_18080_TCP_ADDR: $product.host
            PRODUCT_PORT_18080_TCP_PORT: $product.ports.port
            NAVIGATION_PORT_18090_TCP_ADDR: $navigation.host
            NAVIGATION_PORT_18090_TCP_PORT: $navigation.ports.port
            CART_PORT_18100_TCP_ADDR: $cart.host
            CART_PORT_18100_TCP_PORT: $cart.ports.port
          dependencies:
            product: product
            navigation: navigation
            cart: cart
            checkout: checkout
        scale:
          instances: 1
          cpu: 0.1
          memory: 128
        routing:
          weight: 100
      -
        breed:
          name: catalog:b
          deployable: zutherb/catalog-frontend:latest
          ports:
            port: 80/http
          environment_variables:
            CHECKOUT_DESIGN: amelia
            SHOP_PORT_8080_TCP_ADDR: $checkout.host
            SHOP_PORT_8080_TCP_PORT: $checkout.ports.port
            PRODUCT_PORT_18080_TCP_ADDR: $product.host
            PRODUCT_PORT_18080_TCP_PORT: $product.ports.port
            NAVIGATION_PORT_18090_TCP_ADDR: $navigation.host
            NAVIGATION_PORT_18090_TCP_PORT: $navigation.ports.port
            CART_PORT_18100_TCP_ADDR: $cart.host
            CART_PORT_18100_TCP_PORT: $cart.ports.port
          dependencies:
            product: product
            navigation: navigation
            cart: cart
            checkout: checkout
        scale:
          instances: 1
          cpu: 0.1
          memory: 128
        routing:
          weight: 0
          filters:
          - condition: User-Agent = Chrome
```
It would be could if you can add a validator that notice that the position of the scale section was not ok. But this does not eliminate the properties problem.

<img width="1440" alt="bildschirmfoto 2015-07-11 um 19 35 17" src="https://cloud.githubusercontent.com/assets/489474/8634708/376b9a32-2804-11e5-819c-751fe136c897.png">
<img width="1439" alt="bildschirmfoto 2015-07-11 um 19 34 36" src="https://cloud.githubusercontent.com/assets/489474/8634709/3785d500-2804-11e5-8401-c7ac35d332ef.png">
<img width="1440" alt="bildschirmfoto 2015-07-11 um 19 36 29" src="https://cloud.githubusercontent.com/assets/489474/8634710/37b58480-2804-11e5-8d2c-1a34195abff8.png">
