### ISSUE TITLE
Environment variables not cleaned up after partial delete

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#272]
When deleting parts of a blueprint, as for instance in the Sava tutorial, some environment variables are not cleaned up. This is a problem when you later want to delete the whole deployment as Vamp cannot find the references. Example is the following: sava.BACKEND_1 and sava.BACKEND_2 do no longer exist, they were deleted earlier.

A workaround is to just manually edit out the no longer existing references.

```yaml
- name: 71066d84-1fa2-4e15-b1af-b760a83fc905
  endpoints:
    sava.port: 9060/http
  clusters:
    backend:
      services:
      - state:
          name: Deployed
          started_at: '2015-07-28T21:58:23.476Z'
        breed:
          name: sava-backend:1.3.0
          deployable: docker://magneticio/sava-backend:1.3.0
          ports:
            port: 8080/http
          environment_variables: {}
          constants: {}
          dependencies: {}
        scale:
          cpu: 0.2
          memory: 256.0
          instances: 1
        routing:
          weight: 100
          filters: []
        servers:
        - name: 134f5e46292fb314ae10[0]
          host: 172.17.42.1
          ports:
            '8080': 32787
          deployed: true
        dependencies: {}
        dialects: {}
      routes:
        '8080': 33025
      dialects: {}
    sava:
      services:
      - state:
          name: Deployed
          started_at: '2015-07-28T22:05:34.327Z'
        breed:
          name: sava-frontend:1.3.0
          deployable: docker://magneticio/sava-frontend:1.3.0
          ports:
            port: 8080/http
          environment_variables:
            backend[BACKEND]: http://$backend.host:$backend.ports.port/api/message
          constants: {}
          dependencies:
            backend:
              name: sava-backend:1.3.0
        scale:
          cpu: 0.2
          memory: 256.0
          instances: 1
        routing:
          weight: 100
          filters: []
        servers:
        - name: ba4b1d252493eea2c068[0]
          host: 172.17.42.1
          ports:
            '8080': 32788
          deployed: true
        dependencies:
          backend: backend
        dialects: {}
      routes:
        '8080': 33021
      dialects: {}
  ports:
    sava.port: '33021'
    backend.port: '33025'
  environment_variables:
    sava.backend: http://172.17.42.1:33025/api/message
    sava.BACKEND_1: http://172.17.42.1:33022/api/message
    sava.BACKEND_2: http://172.17.42.1:33023/api/message
  constants: {}
  hosts:
    sava: 172.17.42.1
    backend: 172.17.42.1
```
