### ISSUE TITLE
Define environment variables in service local scope

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#305]
## Use case

A & B services (within the same cluster) need to configured with different environment variable values. If the environment variables have the same name (e.g. my_cool_service.theme) then this is not possible in current implementation. All environment variables have global (deployment) scope and once one value is determined it can't be changed.

## Proposal

- switch the default behaviour to "local first"
- make global scope variables explicit.
- use `~` signs to make clear that values should be filled in by global scope.

```yaml
name: sava:1.0
endpoints:
  frontend.port: 9050/http
environment_variables:     # deployment level variable 
  sava.HEAP: 1400MB        # overrides the breed level
  sava.TIMEOUT: 60

clusters:
  sava:
    services:
      -
        breed:
          name: sava:0.1
          deployable: magneticio/sava:0.1
          ports:
            port: 8080/http
          environment_variables:           
            HEAP: 800MB      # will be overridden by deployment level: 1400MB
            THEME: light     # no deployment level, stays the same
            TIMEOUT: ~       # must be on deployment level, otherwise an error
      -    
        breed:
          name: sava:0.1-experimental_1 # reference

        environment_variables:     # explicit overrides (service level): 
          HEAP: 700MB              # overrides the deployment and breed level value
          THEME: dark              # overrides the breed level value

      -  
        breed:  
          name: sava:0.1-experimental_2
          deployable: magneticio/sava:0.1
          ports:
            port: 8080/http
          environment_variables:
            THEME: light
        environment_variables:     # DSL service level (not breed level) 
          THEME: fluid             # overrides the breed level value

```

**Comment by dragoslav** [comment]
Breeds:

```YAML
name: sava10
deployable: magneticio/sava:1.0.0
ports:
  port: 8080/http
environment_variables:           
  HEAP_SIZE: 800MB
  THEME: light 
```

```YAML
name: sava11
deployable: magneticio/sava:1.0.0
ports:
  port: 8080/http
environment_variables:           
  HEAP_SIZE: 800MB
  THEME: light 
  TIMEOUT: ~
```

Blueprint:

```YAML
name: sava:1.0

endpoints:
  sava.port: 9050/http

env:
  sava.HEAP_SIZE: 1400MB
  sava.TIMEOUT: 60

clusters:
  sava:
    services:
      - breed: sava10
      - breed: sava11
        env: 
          HEAP_SIZE: 700MB
          THEME: dark
```

Deployment:

```YAML
name: 8bfae598-6458-481e-9d49-ad8ca576eeb8
endpoints:
  sava.port: 9050/http
clusters:
  sava:
    services:
    - state:
        name: Deployed
        started_at: '2015-08-26T17:15:53.22+02:00'
      breed:
        name: sava10
        deployable: docker://magneticio/sava:1.0.0
        ports:
          port: 8080/http
        environment_variables:
          HEAP_SIZE: 800MB
          THEME: light
        constants: {}
        dependencies: {}
      environment_variables:
        HEAP_SIZE: 1400MB
        THEME: light
        TIMEOUT: '60'
      scale:
        cpu: 1.0
        memory: 1024.0
        instances: 1
      routing:
        weight: 50
        filters: []
      servers:
      - name: 8bfae598-6458-481e-9d49-ad8ca576eeb8_sava10.560cb9d3-4c05-11e5-9788-56847afe9799
        host: 10.189.194.75
        ports:
          '8080': 31832
        deployed: true
      dependencies: {}
      dialects: {}
    - state:
        name: Deployed
        started_at: '2015-08-26T17:09:37.56+02:00'
      breed:
        name: sava11
        deployable: docker://magneticio/sava:1.0.0
        ports:
          port: 8080/http
        environment_variables:
          HEAP_SIZE: 800MB
          THEME: light
          TIMEOUT: null
        constants: {}
        dependencies: {}
      environment_variables:
        HEAP_SIZE: 700MB
        THEME: dark
        TIMEOUT: '60'
      scale:
        cpu: 1.0
        memory: 1024.0
        instances: 1
      routing:
        weight: 50
        filters: []
      servers:
      - name: 8bfae598-6458-481e-9d49-ad8ca576eeb8_sava11.75be3d92-4c04-11e5-9788-56847afe9799
        host: 10.179.112.50
        ports:
          '8080': 31279
        deployed: true
      dependencies: {}
      dialects: {}
    routes:
      '8080': 33001
    dialects: {}
ports:
  sava.port: '33001'
environment_variables:
  sava.HEAP_SIZE: 1400MB
  sava.TIMEOUT: '60'
hosts:
  sava: 10.40.170.25
```
