### ISSUE TITLE
Dimensions/units in DSL

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#306]
Support for explicit units and dimensions in blueprints so people can define them inline:

```Yaml
    scale:
      cpu: 0.2
      memory: 2GB
      instances: 2
      weight: 40%
    sla:
      type: sliding_window
      metric: response_time
        threshold:
          upper: 1000msec
          lower: 100msec

        window:
          interval: 10sec
          cooldown: 10sec
        reset:
          time: 20sec
```

This will allow better validation (e.g. reject negative values in some cases etc.)
