### ISSUE TITLE
New DSL reference implementation

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#318]
"reference" or "ref" instead of "name" for all artifact references:

```YAML
name: nomadic-frostbite

clusters:
  notorious:
    services:
      breed: 
        ref: nocturnal-viper  # "reference" or "ref"
          
      routing:
        filters:
          - android
          - reference: ios    # "reference" or "ref"
```
