### ISSUE TITLE
Sticky routing for A/B testing

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#319]
When going through the tutorial it becomes clear that the A/B routing based on weight does distributed the load naively. Every request goes to another service. This will lead in a site from B with the css from A.

This makes it harder to use A/B testing, as you really need to define a filter to help the routing. It would be nice if there was an option to choose for sticky routing without placing the burden on the app developer to provide a session. It is possible to configure haproxy to do this.

Note: The requirement is to sticky load on service level. If there are multiple servers for a server, the load can still be distributed among the servers of the same service.

## Rationale

We need this feature because:
It will make it a lot easier for the users to introduce A/B testing for webbapps.

## Features

Specify that this HTTP routing should be sticky (opt-in, default is non-sticky). 

## Implementation direction

Place a session cookie on first request and use that for routing http requests.  This will only work for http traffic, but I guess that is where this feature is mostly needed.

## References
- http://blog.haproxy.com/2012/03/29/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/

**Comment by jgordijn** [comment]
Nice to see that this issue is placed on roadmap. I really think that this is necessary to make weight distribution usable. When is 0.8.1 scheduled?

**Comment by dragoslav** [comment]
We are finalising 0.8.0 right now and then we will have 2-3 weeks of development for 0.8.1.
We planned for it the new Gateway API and several issues like this one. I expect release in the first half of December.

**Comment by olafmol** [comment]
@jgordijn to get a better understanding: so if a visitor lands on version A of a service, it should pull in all the related resources of this service (such as CSS, Javascript libs etc.). This assumes that the VAMP-user doesn't need to apply (name-based) versioning on his/her included resources by default. Is that a correct assumption?

Furthermore: is it a wish to have visitors becoming sticky? I.e. after landing for the first time on a specific version of a service, if they return they will see the same version every time, until the rules are changed. Please let us know what is useful for you.

**Comment by jgordijn** [comment]
@olafmol I don't really see what name-based version has to do with this? If I use name based version I will get 404 with the current implementation.

During the session of the user I want this user to have a consistent experience. For instance, if I change the search engine, I want the user to see the same search results&order during his/her session. With the current implementation his first request may land on search version A and the second search may land on version B. This will be very confusing.

**Comment by olafmol** [comment]
@jgordijn i meant this example, considering CSS: service A frontend points to "my_stylesheet_serviceA.css" and service B frontend-code points to "my_stylesheet_serviceB.css".

**Comment by jgordijn** [comment]
@olafmol I still don't understand what you want to achieve with changing the name. In my mind the name change is used to go around the caching problem. If you try to use naming for routing, it places a lot of burden on the development. You need to change every name of every page in you application to stay inside the same service. Besides that, it goes even further to services behind the frontend (e.g. search).

**Comment by olafmol** [comment]
@jgordijn I agree about removing the burden from the developer.

**Comment by dragoslav** [comment]
Example blueprint:

```yaml
name: sava

clusters:
  sava:
    routing:
      port:
        sticky: instance # service or instance
        routes:
          sava:1.0.0:
            weight: 50
          sava:1.1.0:
            weight: 50

    services:
      -
        breed:
          name: sava:1.0.0
          deployable: docker://magneticio/sava:1.0.0
          ports:
            port: 8080/http
          environment_variables:
            SAVA_DEBUG: true
        scale:
          cpu: 0.1       
          memory: 64  
          instances: 2

      -
        breed:
          name: sava:1.1.0
          deployable: docker://magneticio/sava:1.1.0
          ports:
            port: 8080/http
          environment_variables:
            SAVA_DEBUG: true
        scale:
          cpu: 0.1       
          memory: 64  
          instances: 2
```
Use `sava.port` or port mapping from deployment to get the port (there is no endpoint support until #167)
For instance `sava.port: '33001'`

```yaml
  name: 32617e49-0565-4036-8204-8f178882511f
  clusters:
    sava:
      services:
      - state:
          intention: Deploy
          since: '2015-12-10T15:56:49.007+01:00'
          step:
            name: Done
            since: '2015-12-10T15:56:59.687+01:00'
        breed:
          name: sava:1.0.0
          deployable: docker://magneticio/sava:1.0.0
          ports:
            port: 8080/http
          environment_variables:
            SAVA_DEBUG: 'true'
          constants: {}
          dependencies: {}
        environment_variables:
          SAVA_DEBUG: 'true'
        scale:
          cpu: 0.1
          memory: 64.0
          instances: 2
        instances:
        - name: 32617e49-0565-4036-8204-8f178882511f_6fd83b1fd01f7dd9eb7f.3ffe8b7e-9f4e-11e5-af6f-024290f75bf7
          host: 192.168.99.100
          ports:
            '8080': 31265
          deployed: true
        - name: 32617e49-0565-4036-8204-8f178882511f_6fd83b1fd01f7dd9eb7f.3ffeb28f-9f4e-11e5-af6f-024290f75bf7
          host: 192.168.99.100
          ports:
            '8080': 31591
          deployed: true
        dependencies: {}
        dialects: {}
      - state:
          intention: Deploy
          since: '2015-12-10T15:56:49.005+01:00'
          step:
            name: Done
            since: '2015-12-10T15:57:01.25+01:00'
        breed:
          name: sava:1.1.0
          deployable: docker://magneticio/sava:1.1.0
          ports:
            port: 8080/http
          environment_variables:
            SAVA_DEBUG: 'true'
          constants: {}
          dependencies: {}
        environment_variables:
          SAVA_DEBUG: 'true'
        scale:
          cpu: 0.1
          memory: 64.0
          instances: 2
        instances:
        - name: 32617e49-0565-4036-8204-8f178882511f_2e2fc6ab8a1cdbe79dc3.42fcd760-9f4e-11e5-af6f-024290f75bf7
          host: 192.168.99.100
          ports:
            '8080': 31452
          deployed: true
        - name: 32617e49-0565-4036-8204-8f178882511f_2e2fc6ab8a1cdbe79dc3.42fd4c91-9f4e-11e5-af6f-024290f75bf7
          host: 192.168.99.100
          ports:
            '8080': 31593
          deployed: true
        dependencies: {}
        dialects: {}
      routing:
        port:
          sticky: instance
          routes:
            sava:1.0.0:
              weight: 50
              filters: []
            sava:1.1.0:
              weight: 50
              filters: []
      port_mapping:
        '8080': 33001
      dialects: {}
  ports:
    sava.port: '33001'
  environment_variables: {}
  hosts:
    sava: 192.168.99.100

```
