### ISSUE TITLE
Implement Docker dialect interpolation

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#321]
Marathon dialect suports interpolation, for instance:
```
cmd: $CMD // 'CMD" is defined in breed
```

**Comment by dragoslav** [comment]
```YAML
name: mysq

endpoints:
  mysql.port: 9050

environment_variables:
  mysql.password: SECRET
  
clusters:

  mysql:
    services:
      breed:
        name: mysq:5.7.8
        deployable: mysql:5.7.8
        ports:
          port: 3306/tcp
        environment_variables:
          password: ~

      dialects:
        docker:
          Env: 
          - MYSQL_ROOT_PASSWORD=$password
```
will be resolved to (docker inspect):

```YAML
"Env": [
  "password=SECRET",
  "MYSQL_ROOT_PASSWORD=SECRET",
  ...
]
```

There is also a merge of environment variables defined in the breed (password) and in the dialect (MYSQL_ROOT_PASSWORD).
