### ISSUE TITLE
Updating a blueprint endpoint port in the UI does not actually persist

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#331]
Updating an endpoint port from value x to y generates a 200 OK in the backend, but then rolls back the edit somehow.

example:

```yaml
name: monarchs:1.0
endpoints:
  frontend.port: 9054/http
clusters:
  frontend:
    services:
    - breed:
        name: monarch_front:0.1
        deployable: docker://magneticio/monarch:0.1
        ports:
          port: 8080/http
        environment_variables:
          MONARCH_DEPENDS_ON_HOST: $backend.host
          MONARCH_DEPENDS_ON_PORT: $backend.ports.jdbc
        constants: {}
        dependencies:
          backend:
            name: monarch_backend:0.3
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 256.0
        instances: 1
      routing:
        weight: 100
        filters: []
      dialects: {}
    - breed:
        name: monarch_front:0.2
        deployable: docker://magneticio/monarch:0.2
        ports:
          port: 8080/http
        environment_variables:
          MONARCH_DEPENDS_ON_HOST: $backend.host
          MONARCH_DEPENDS_ON_PORT: $backend.ports.jdbc
        constants: {}
        dependencies:
          backend:
            name: monarch_backend:0.3
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 256.0
        instances: 1
      routing:
        weight: 0
        filters:
        - condition: user-agent = Chrome
      dialects: {}
    dialects: {}
  backend:
    services:
    - breed:
        name: monarch_backend:0.3
        deployable: docker://magneticio/monarch:0.3
        ports:
          jdbc: 8080/http
        environment_variables: {}
        constants: {}
        dependencies: {}
      environment_variables: {}
      dialects: {}
    dialects: {}
environment_variables: {}
```
