### ISSUE TITLE
deployments with multiple endpoints get all traffic routed to first port 

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#348]
Original issue by Harry:

Deploying two separate endpoints mapped to separate ports in a service results in both ports being mapped to the same port. This happens when using either the marathon driver or docker driver.

Use the following blueprint to reproduce, you can see both port 8080 and 8081 being mapped to 32959.

```yaml
name: monarchs:1.1
endpoints:
  frontend.port: 9050/http
  frontend.extra: 9051/http
clusters:
  frontend:
    services:
    - breed:
        name: monarch_front:0.1
        deployable: docker://magneticio/monarch:0.1
        ports:
          port: 8080/http
          extra: 8081/http
        environment_variables: {}
        constants: {}
        dependencies: {}
      dialects: {}
    dialects: {}
environment_variables: {}
```

The result is the following:. You can see

```json
{
    "name": "1ab4ec08-0737-436d-8771-936545c84990",
    "endpoints": {
        "frontend.port": "9050/http",
        "frontend.extra": "9051/http"
    },
    "clusters": {
        "frontend": {
            "services": [
                {
                    "state": {
                        "name": "Deployed",
                        "started_at": "2015-08-24T10:15:43.441Z"
                    },
                    "breed": {
                        "name": "monarch_front:0.1",
                        "deployable": "docker://magneticio/monarch:0.1",
                        "ports": {
                            "port": "8080/http",
                            "extra": "8081/http"
                        },
                        "environment_variables": {},
                        "constants": {},
                        "dependencies": {}
                    },
                    "scale": {
                        "cpu": 0.3,
                        "memory": 512,
                        "instances": 1
                    },
                    "routing": {
                        "weight": 100,
                        "filters": []
                    },
                    "servers": [
                        {
                            "name": "39b10fbf046b3a4c7567[0]",
                            "host": "172.17.42.1",
                            "ports": {
                                "8080": 32959,
                                "8081": 32959
                            },
                            "deployed": true
                        }
                    ],
                    "dependencies": {},
                    "dialects": {}
                }
            ],
            "routes": {
                "8080": 33016,
                "8081": 33017
            },
            "dialects": {}
        }
    },
    "ports": {
        "frontend.port": "33016",
        "frontend.extra": "33017"
    },
    "environment_variables": {},
    "constants": {},
    "hosts": {
        "frontend": "172.17.42.1"
    }
}
```
