### ISSUE TITLE
Wrong router mapping when exposing multiple ports from one service 

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#353]
Given a docker that exposes on 2 ports. I have a blueprint which looks like:
```yaml
name: noding:1.0
endpoints:
  node.port1: 9060/http
  node.port2: 9090/http
clusters:
  node:
    services:
      breed:
        name: testing
        deployable: node-hello
        ports:
          port1: 8080/http                
          port2: 8081/http  
```

When I deploy this, all requests go to port 8080. See the router output below:

notice that routes `4f0ffa6-e743-4e6c-9a2f-30a8f866c8d9_node_8080` and `54f0ffa6-e743-4e6c-9a2f-30a8f866c8d9_node_8081` both route to the same `port`.

```json
[
  {
    "name": "54f0ffa6-e743-4e6c-9a2f-30a8f866c8d9_9060",
    "port": 9060,
    "protocol": "http",
    "httpQuota": {},
    "tcpQuota": {},
    "filters": [],
    "services": [
      {
        "name": "node.ports.port1",
        "weight": 100,
        "servers": [
          {
            "name": "54f0ffa6-e743-4e6c-9a2f-30a8f866c8d9_9060",
            "host": "172.17.42.1",
            "port": 33012
          }
        ]
      }
    ]
  },
  {
    "name": "54f0ffa6-e743-4e6c-9a2f-30a8f866c8d9_9090",
    "port": 9090,
    "protocol": "http",
    "httpQuota": {},
    "tcpQuota": {},
    "filters": [],
    "services": [
      {
        "name": "node.ports.port2",
        "weight": 100,
        "servers": [
          {
            "name": "54f0ffa6-e743-4e6c-9a2f-30a8f866c8d9_9090",
            "host": "172.17.42.1",
            "port": 33013
          }
        ]
      }
    ]
  },
  {
    "name": "54f0ffa6-e743-4e6c-9a2f-30a8f866c8d9_node_8080",
    "port": 33012,
    "protocol": "http",
    "httpQuota": {},
    "tcpQuota": {},
    "filters": [],
    "services": [
      {
        "name": "testing",
        "weight": 100,
        "servers": [
          {
            "name": "98a398ef90d181c78596902c49a556aa9afa6985",
            "host": "172.17.42.1",
            "port": 32778
          }
        ]
      }
    ]
  },
  {
    "name": "54f0ffa6-e743-4e6c-9a2f-30a8f866c8d9_node_8081",
    "port": 33013,
    "protocol": "http",
    "httpQuota": {},
    "tcpQuota": {},
    "filters": [],
    "services": [
      {
        "name": "testing",
        "weight": 100,
        "servers": [
          {
            "name": "98a398ef90d181c78596902c49a556aa9afa6985",
            "host": "172.17.42.1",
            "port": 32778
          }
        ]
      }
    ]
  }
]
```
