### ISSUE TITLE
Deployment not recognised as deployed with long clustername 

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#359]
The following blueprint deploys correctly, but VAMP doesn't recognise it as deployed (status remains `readyfordeployment` and eventually moves to `error`). When undeploying it also doesn't delete all routes. Changing `sava_with_a_very_long_name` to `sava` fixes this problem.

```yaml
---
name: sava:1.0
endpoints:
  sava_with_a_very_long_name.port: 9050/http
clusters:
  sava_with_a_very_long_name:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 8080/http
      scale:
        cpu: 0.2       
        memory: 256  
        instances: 1


```
