### ISSUE TITLE
Router crashes and Undeploy doesn't work anymore

### ISSUE THREAD

**Issue by Ozzadar** [magneticio/vamp#397]
I deployed a simple ghost blog 

```
name: ghost:1.0
endpoints:
  ghost.port: 8079/http
clusters:
  ghost:
    services:
    - breed:
        name: ghost-breed
        deployable: docker://ghost
        ports:
          port: 2368/http
        environment_variables: {}
        constants: {}
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.2
        memory: 256.0
        instances: 1
      dialects: {}
    dialects: {}
environment_variables: {}
```
After this deployment, vamp-router crashed and refuses to come back up.

Additionally, I cannot undeploy any deploys. They disappear briefly and reappear right afterwards.
