### ISSUE TITLE
The UI should give a status report upon initial load 

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#40]
When loading the first screen, the UI should state wether it can connect to the REST api, what version it is and other details regarding the status of Vamp. This info should come from the /hi endpoint.

**Comment by dragoslav** [comment]
For sake of consistency we should use /info endpoint (like in Router, Pulse, Marathon...)
We have both /hi and /info right now. We should remove /hi.

**Comment by tnolet** [comment]
yes, that's fine. We make the endpoint `/info` but keep the friendly "hi" message as part of the /info json object.

**Comment by tnolet** [comment]
We should check the `/info` endpoint. There are some scenarios:
- either no answer at all => general error: no backend
- per service: router, container driver and pulse => can all be in "error" state.

**Comment by tnolet** [comment]
We'll show the following items from the information endpoint:

```yaml
---
  message: "Hi, I'm Vamp! How are you?"
  jvm: 
    runtime: 
      start_time: 1434034485549
      up_time: 727684
  persistence: 
    type: "jdbc"
    url: "jdbc:h2:./vamp-core-db"
    database: 
      name: "H2"
      version: "1.3.166 (2012-04-08)"
      schema_version: "V2 / 2015-06-11 14:54:58.259 [Up to date]"
  router: 
    memmax_mb: "0"
    name: "HAProxy"
    version: "1.5.12"
    sess_rate: "0"
    idle_pct: "100"
    uptime: "0d 0h12m07s"
  pulse: 
    jvm: 
      runtime: 
        start_time: 1434034485549
        up_time: 727707
    elastic_search: 
      cluster_name: "elasticsearch"
      name: "Mad-Dog"
      version: 
        number: "1.5.1"
        lucene_version: "4.10.4"
      status: 200
    stream: 
      driver: "sse"
  container_driver: 
    type: "docker"
```
