### ISSUE TITLE
Redeploy gives issues

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#409]
Deployed a blueprint like below. When I deploy first time everything is working just fine. When I undeploy and deploy again I get unpredictable 503 answers. Sometimes I get a 200 and sometimes 503.

``` yml
name: foo:2.0
endpoints:
  baz.http: 9988/http
clusters:
  bar:
    services:
    - breed:
        name: bar:1.0
        deployable: docker://jgordijn/bar:1.0
        ports:
          http: 8080/http
        environment_variables:
          JAVA_OPTS: -Xmx64m -Xms64m
        constants: {}
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 128.0
        instances: 1
      dialects:
        marathon:
          uris:
          - file:///etc/docker.tar.gz
    dialects: {}
  baz:
    services:
    - breed:
        name: baz:1.0
        deployable: docker://jgordijn/baz:1.1
        ports:
          http: 3000/http
        environment_variables:
          JAVA_OPTS: -Xmx512m -Xms256m
          BAR_HOST: $bar.host
          BAR_PORT: $bar.ports.http
        constants: {}
        dependencies:
          bar: bar:1.0
      environment_variables: {}
      scale:
        cpu: 0.5
        memory: 768.0
        instances: 1
      dialects:
        marathon:
          uris:
          - file:///etc/docker.tar.gz
    dialects: {}
environment_variables: {}
```
