### ISSUE TITLE
Blueprint with disappearing SLA

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#413]
The following blueprint will remove the SLA part after saving and re-opening it:
```yaml
---
name: scaledemo
endpoints:
  trifork.port: 9060/http
clusters:
  trifork:
    - breed:
      name: sava:1.0.0
      deployable: docker://magneticio/sava:1.0.0
      ports:
        port: 8080/http
sla:
  # Type of SLA.
  type: response_time_sliding_window
  threshold:
    upper: 4  # Upper threshold in milliseconds.
    lower: 2    # Lower threshold in milliseconds.
  window:
    interval: 10 # Time period in seconds used for
                  # average response time aggregation.
    cooldown: 60 # Time period in seconds. During this
                  # period no new escalation events will
                  # be generated. New event may be expected
                  # not before cooldown + interval time has
                  # been reached after the last event.

  # List of escalations.
  escalations:
    - type: scale_instances
      minimum: 1
      maximum: 5
      scale_by: 1
```

**Comment by olafmol** [comment]
Scaling examples in docs also don't work correctly/as expected, we need to update them so they can work with our Sava examples: http://vamp.io/documentation/using-vamp/sla-and-escalations/

**Comment by dragoslav** [comment]
SLA needs to be defined on the cluster level - in the example above it's on top level.
 This works:
```yaml
name: scaledemo
endpoints:
  trifork.port: 9060/http
clusters:
  trifork:
    breed:
      name: sava:1.0.0
      deployable: docker://magneticio/sava:1.0.0
      ports:
        port: 8080/http
    sla:
      # Type of SLA.
      type: response_time_sliding_window
      threshold:
        upper: 4  # Upper threshold in milliseconds.
        lower: 2    # Lower threshold in milliseconds.
      window:
        interval: 10 # Time period in seconds used for
                      # average response time aggregation.
        cooldown: 60 # Time period in seconds. During this
                      # period no new escalation events will
                      # be generated. New event may be expected
                      # not before cooldown + interval time has
                      # been reached after the last event.

      # List of escalations.
      escalations:
        - type: scale_instances
          minimum: 1
          maximum: 5
          scale_by: 1
```
Also, in case of single service, it's better to have non-list representation (like in my example) or full definition with "services" element:
```yaml
...
  trifork:
    services:
      - 
        breed:
          name: sava:1.0.0
          deployable: docker://magneticio/sava:1.0.0
          ports:
            port: 8080/http
    sla:
...
```

And unfortunately we have the same issue in our documentation.
