### ISSUE TITLE
Do canary release via CLI

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#414]
Let's consider blueprint1 (see below) is running. I now want to deploy authentication:1.1. What I do is the following:
* Create new Breed
* Create blueprint with only the new breed (Blueprint1 with version 1.1)
* Merge it into deployment with cli: `vamp deploy authentication:1.1 --deployment dde334f6-8dca-4f04-a0f5-93df2f4801c1`

As you can see below this leads to a version 1.1 deployed with weight 0. Now when I want to change the weight I have to parse the yml and update the weights. It would be nice if the CLI provides with a convenient way to do this. For example being ably to read out the weights by version and being able to generate a new blueprint that can be merged with the new weights. The logic must be written by the user (me), but VAMP can help me so that I don't have to write a parser for the blueprint. 

Blueprint1
```yaml
---
name: authentication:1.0            # Custom blueprint name
endpoints:
  authentication.http: 9980/http
clusters:
  authentication:                         # Custom cluster name.
    services:                             # List of services
      - breed:
          reference: authentication:1.0
        routing:
          weight: 100
        scale:                            # Scale for this service.
          cpu: 0.1                        # Number of CPUs per instance.
          memory: 128                     # Memory in MB per instance.
          instances: 1                    # Number of instances
```

Deployment after merge
```yaml
name: dde334f6-8dca-4f04-a0f5-93df2f4801c1
endpoints:
  authentication.http: 9980/http
clusters:
  authentication:
    services:
    - breed:
        name: authentication:1.0
        deployable: docker://jgordijn/authentication:1.0
        ports:
          http: 8080/http
        environment_variables:
          JAVA_OPTS: -Xmx64m -Xms64m
        constants: {}
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 128.0
        instances: 1
      routing:
        weight: 100
        filters: []
      dialects:
        marathon:
          uris:
          - file:///etc/docker.tar.gz
    - breed:
        name: authentication:1.1
        deployable: docker://jgordijn/authentication:1.1
        ports:
          http: 8080/http
        environment_variables:
          JAVA_OPTS: -Xmx128m -Xms128m
        constants: {}
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 128.0
        instances: 1
      routing:
        weight: 0
        filters: []
      dialects:
        marathon:
          uris:
          - file:///etc/docker.tar.gz
    dialects: {}
environment_variables: {}
```
