### ISSUE TITLE
sava_monolith post to vamp gives error on post

### ISSUE THREAD

**Issue by buuhsmead** [magneticio/vamp#43]
The blueprint on page http://vamp.io/documentation/getting-started/deploying/ gives an error.
The error (from docker logs bamp) is:
16:10:53.087 | ERROR | io.vamp.common.notification.Notification |                                          | Error: mapping values are not allowed here
 in 'reader', line 1, column 33:
    name: sava_monolith_1_1endpoints:  sava.ports.port: 9050clusters ...
                                    ^
The error from curl: 
curl -X POST -H "Content-Type: application/x-yaml" http://localhost:8081/api/v1/deployments -d @1.1_monolith.yaml
"The request content was malformed: Error: mapping values are not allowed here\n in 'reader', line 1, column 33:\n    name: sava_monolith_1_1endpoints:  sava.ports.port: 9050clusters ... \n                                    ^\n"

**Comment by tnolet** [comment]
Might have been a copy & paste error. Just tested it with RC3 release and it works correctly:

```YAML
name: sava_monolith_1_0

endpoints:
  sava.ports.port: 9050

clusters:

  sava:
    services:
      breed:
        name: sava_monolith_1_0
        deployable: magneticio/sava-1.0_monolith:0.7.0
        ports:
          name: port
          value: 80/http
          direction: OUT
```

please make sure all white space and CRLF's are correct.
