### ISSUE TITLE
SLA doesn't seem to be working

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#436]
Given the deployment below. When I put load on the app the response times go above 15ms. VAMP doesn't scale up.

Also UI doesn't give info about escalations.

```yaml
name: 8d54097d-0834-4292-920f-d585d677407c
endpoints:
  frontend.http: 9050/http
clusters:
  frontend:
    services:
    - breed:
        name: frontend:1.0
        deployable: docker://application/frontend:1.0
        ports:
          http: 3000/http
        environment_variables: {}
        constants: {}
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.1
        memory: 256.0
        instances: 1
      routing:
        weight: 100
        filters: []
      dialects:
        marathon:
          uris:
          - file:///etc/docker.tar.gz
    sla:
      type: response_time_sliding_window
      window:
        interval: 10
        cooldown: 10
      threshold:
        upper: 15
        lower: 5
      escalations:
      - type: scale_instances
        minimum: 1
        maximum: 3
        scale_by: 1
```

**Comment by olafmol** [comment]
Hi Jeroen, thanks for reporting. We are aware that the scaling part of VAMP needs some love&attention ;) Our current focus is on the canary-part, stability and high-availability. We're currently making some great steps in nailing these. When done, the auto/micro-scaling part will get it's deserved attention again.

**Comment by dragoslav** [comment]
Fixed few bugs, example:

```yaml
name: sava:1.0

gateways:
  9050: sava/port

clusters:

  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 8080/http
        environment_variables:
          debug[SAVA_DEBUG]: true
    
      scale:
          cpu: 0.2
          memory: 512
          instances: 2

    sla:
      type: response_time_sliding_window
      threshold:
        upper: 10 # intentionally low to trigger (almost) always on any request
        lower: 5
      window:
        interval: 30
        cooldown: 30

      escalations:
        - 
          type: scale_instances
          minimum: 1
          maximum: 3
          scale_by: 1
```
