### ISSUE TITLE
2 backends blueprint from tutorial does not show backend metrics in GUI

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#442]
The blueprint from the tutorial part 1.3 (splitting 2 backends) does not show metrics in the GUI for the backends. The frontend part does show metrics as expected.

Deployment:
```yaml
name: c4c3ed3c-e56e-47ce-8fb7-f9aafaea6034
endpoints:
  sava.port: 9060/http
clusters:
  sava:
    services:
    - breed:
        name: sava-frontend:1.2.0
        deployable: docker://magneticio/sava-frontend:1.2.0
        ports:
          port: 8080/http
        environment_variables:
          BACKEND_1: http://$backend1.host:$backend1.ports.port/api/message
          BACKEND_2: http://$backend2.host:$backend2.ports.port/api/message
        constants: {}
        dependencies:
          backend1: sava-backend1:1.2.0
          backend2: sava-backend2:1.2.0
      environment_variables: {}
      scale:
        cpu: 0.2
        memory: 256.0
        instances: 1
      routing:
        weight: 100
        filters: []
      dialects: {}
    dialects: {}
  backend1:
    services:
    - breed:
        name: sava-backend1:1.2.0
        deployable: docker://magneticio/sava-backend1:1.2.0
        ports:
          port: 8080/http
        environment_variables: {}
        constants: {}
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.2
        memory: 256.0
        instances: 1
      routing:
        weight: 100
        filters: []
      dialects: {}
    dialects: {}
  backend2:
    services:
    - breed:
        name: sava-backend2:1.2.0
        deployable: docker://magneticio/sava-backend2:1.2.0
        ports:
          port: 8080/http
        environment_variables: {}
        constants: {}
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.2
        memory: 256.0
        instances: 1
      routing:
        weight: 100
        filters: []
      dialects: {}
    dialects: {}
environment_variables: {}
```
