### ISSUE TITLE
Move routing to cluster level

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#444]
In DSL it's possible to define `routing` on service level: weight and filters. There are additional parameters that make sense only on cluster level: stickiness (custom cookies in more generic sense), balance algorithms etc. It makes more sense to combine everything into one `routing` definition on cluster level then to have partial definition on cluster and each service.

Example - current:

```yaml

my_cluster:

    routing:
      sticky: server
      balance: roundrobin

    services:
      -
        breed: breed_1
        routing:
          filters:
            - android
      -
        breed: breed_2
        routing:
          filters:
            - ios
      -
        breed: breed_3
```

Proposed

```yaml

my_cluster:

    routing:
      sticky: server
      balance: roundrobin
      routes:
        breed_1:
          weight: 90
          filters: 
          - android
        breed_2:
          weight: 10
          filters:  
          - ios

    services:
      - breed: breed_1
      - breed: breed_2
      - breed: breed_3
```

This is also more aligned with Gateway DSL - keeping all definitions in one group.
