### ISSUE TITLE
Shorten routing notation

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#446]
current:
```yaml
routing:  
  weight: 50
  filters:
  - android
  - ios
```
proposal:
```yaml
routing[50%]:  
- android
- ios
```
or

```yaml
routing/50%:  
- android
- ios
```
