### ISSUE TITLE
ansible vamp-router 

### ISSUE THREAD

**Issue by buuhsmead** [magneticio/vamp#45]
This is a part of an ansible playbook I use to run a mesos/marathon cluster with vamp. Vamprouter should for now < 0.7.0-RC2  not be running on a cluster but directly on a docker host. At least on a mesos cluster it moves around and vamp does not follow the movement at this moment.
```yaml
- name: start docker image vamp-router
  docker:
    name: vamprouter
    image: magneticio/vamp-router:latest
    pull: always
    state: reloaded
    memory_limit: "512MB"
    count: 1
    detach: true
    ports:
      - 80:80
      - 1988:1988
      - 10001:10001
```
The same for vamp. Both are running on dedicated separate docker hosts: So I run vamp-router on host 'vampe' and vamp on host 'vampa'.
```yaml
- name: run vamp on host vampa
  docker:
    name: vamp
    image: magneticio/vamp:latest
    pull: always
    state: reloaded
    count: 1
    ports:
      - 81:80
      - 8081:8080
      - 10002:10001
      - 8084:8083
    env:
      VAMP_MARATHON_URL: 'http://{{hostvars.vampa.ansible_fqdn}}:8080'
      VAMP_ROUTER_URL: 'http://{{hostvars.vampe.ansible_fqdn}}:10001'
      VAMP_ROUTER_HOST: '{{hostvars.vampe.ansible_fqdn}}'
```
