### ISSUE TITLE
Allow implicit port routing for single port services

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#463]
If services have only one port, then port name can be omitted in routing.

Without feature:

```yaml
clusters:
  sava:
    routing:
      web:
        sticky: server

    services:
      breed: 
        name: magneticio/sava:1.0.0
        ports:
          web: 8080
```
With:

```yaml

clusters:
  sava:
    routing:
      sticky: server       # applies on web port implicitly 
    services:
      breed: 
        name: magneticio/sava:1.0.0
        ports:
          web: 8080
```
