### ISSUE TITLE
DSL parser for the new Gateway API

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#464]
#167

```yaml
gateways:
  my_gateway_1:
    port: 8080/http
    sticky: service
    balance: roundrobin
    routes:
     $gateway:
       weight: 10
       filters:
       - condition: ... # anonymous filter, it can be by name, e.g. filter: android
     # deployment gateway
     $deployment/$gateway:
       ...
     # cluster port of a deployment
     $deployment/$cluster/$port:
       ...
     # service port of deployment/cluster
     $deployment/$cluster/$service/$port:
       ...
```
