### ISSUE TITLE
Use implicit "this" reference for deployment gateways

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#474]
```yaml
name: sava:1.0

gateways:
  9050:
    routes:
    - sava/web

clusters:
  sava:
    services:
      ...
```
Assuming `sava/web` route should point to the `sava` cluster and `web` port, there are few issues:

- `sava/port` can't be distinguished from  `sava` deployment and deployment gateway`web` (here we define deployment gateway `9050`)
- we don't now the deployment name once gateway is deployed - can be a UUID or any other given name (`PUT .../deployments/$name`), so actual route should be `$deployment/sava/web`.

Solution is to use the following route notations:

- `sava/web` means `sava` deployment and `web` deployment gateway
- `./sava/web` means local deployment reference to cluster `sava` and port `web`. Placeholder `.` will be replaced once the gateway is created (e.g. route will become `$deployment/sava/web`).

Note: this is relevant only if we support generic route format as in Gateway API (currently only local routes are supported).
