### ISSUE TITLE
Renaming: condition instead of filter

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#476]
Current:

```yaml
route:  
  filter_strength: 5%
  filters:
  - android
  - reference: test_users
  - condition: user.agent == ios
```

Proposed:

```yaml
route:  
  condition_strength: 5%
  conditions:
  - android
  - reference: test_users
  - condition: user.agent == ios
```
