### ISSUE TITLE
After restarting Vamp, gateways are recreated and HAProxy may fail to load due to inconsistent configuration

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#478]
1) deploy:

```yaml
name: sava:1.0

gateways:
  9050: sava/port

clusters:

  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 8080/http
```
2) restart Vamp without restarting anything else
3) HAProxy may have an empty configuration and any gateway will be disabled
