### ISSUE TITLE
Support for external route endpoint

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#494]
Gateway API supports only routes managed by Vamp (deployments etc.).
Let's say we have 3 instances of some external app/service. 
To access them, app can use some service discovery mechanism and alternatively it could connect to the gateway managed by Vamp - simple gateway agent host/port.

External route are specified between square brackets, e.g. 
```yaml
name: mesos
port: 8080/http
sticky: route

routes:
  "[192.168.99.100:5050]":
    weight: 100%
```
