### ISSUE TITLE
Rewrite URL path in DSL without specifying HAProxy native configuration  

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#495]
Similar to something we already have for user agent.

Simple 50/50 with rewrite rule - `/v1` treated as `/`:

```yaml
routing:
  routes:
    sava:1.0.0:
      weight: 50%
      filters:
      - condition: rewrite / if path -i /v1
    sava:1.1.0:
      weight: 50%
      filters:
      - condition: rewrite / if path -i /v1
```

With additional condition - in case of `Firefox` and supports as well `/v1.1` paths:
```yaml
routing:
  routes:
    sava:1.0.0:
      weight: 100%
    sava:1.1.0:
      weight: 0%
      filters:
      - condition: User-Agent = Firefox
      - condition: rewrite / if path -i /v1.1
```
Just plain rewrite and with specific service - `/v1.1` send to `sava:1.1.0` as `/`:
```yaml
routing:
  routes:
    sava:1.0.0:
      weight: 100%
    sava:1.1.0:
      weight: 0%
      filters:
      - condition: path -i /v1.1
      - condition: rewrite / if path -i /v1.1
```
