### ISSUE TITLE
Sticky sessions: rename 'service' to 'route'

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#503]
```yaml
routing:
  sticky: service
  routes:
    sava:1.0.0:
      weight: 100%
    sava:1.1.0:
      weight: 50%
```

In above example 'service' makes sense, while in:

```yaml
name: main
port: 9050
sticky: service
routes: 
  vamp/sava1/port: 
    weight: 50%
  vamp/sava2/port: 
    weight: 50%
}
```
'service' doesn't make any sense because there are no services, but routes point to `vamp` deployment, and `sava1` and `sava2` clusters (port `port`).

In both cases `sticky: route` makes sense.
