### ISSUE TITLE
Separate rewrites from filters, consider using 'override' declaration

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#508]
Now `filter/rewrite` is distinguished by context which could be vague:

```yaml
route:
  weight: 0%
  filters:
  - condition: user-agent == Firefox           # filter on header
  - condition: path -i /api/v2                 # filter on path
  - condition: rewrite /api if path -i /api/v2 # request transformation
```

Proposed:

```yaml
route:
  weight: 0%
  filters:
  - condition: user-agent == Firefox # filter on header
  - condition: path -i /api/v2       # filter on path
  rewrites:
  - path: /api if path -i /api/v2    # path transformation
```

This will allow cleaner declarations and implementation.
Also it is easier to extend  `routes` with new features, e.g. overriding headers, cookies etc.

**Comment by olafmol** [comment]
We also might consider more explicit include/exclude filtering (f.e. like http://docs.launchdarkly.com/docs/targeting-users) and more explicit AND / OR filtering (like f.e. https://vwo.com/knowledge/conditions-for-defining-segments/)

**Comment by dragoslav** [comment]
include A, exclude B
include C, exclude D

you can write as:
```yaml
- condition: A
- condition: not B
- condition: C
- condition: not D
# or
- condition: A and not B
- condition: C and not D
# or
- condition: A and not B and C and not D 
```
And we support NOT/AND/OR and arbitrary grouping: 
```yaml
- condition: not (A or B) and ((C or not D) or E)
# or
- condition: !(A | B) & ((C | !D) | E)
```
Adding explicit `include` and `exclude` sections, or array of pairs will make DSL more verbose especially for complex expressions. On the other hand, having list of conditions allows easy add/append of the next expression(s) - useful for higher order interfacing (e.g. UI).
