### ISSUE TITLE
Allow pattern matching breed dependency

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#519]
Currently only the full match is allowed `backend:1.0.0`: 

```yaml
name: frontend:1.0.0
deployable: company/frontend:1.0.0
dependencies:
  backend: backend:1.0.0
```

It should be possible to make it less strict:

```yaml
name: frontend:1.0.0
deployable: company/frontend:1.0.0
dependencies:
  backend: backend:1.*
```

In the example `*` is a quantifier that replaces any suffix.
Expression can be interpreted as "any breed name starting with `backend:1.`
