### ISSUE TITLE
blueprint from tutorial only works in edit deployment

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#522]
In our tutorial the second example blueprint only works when pasting it in a running deployment from the first example blueprint. When creating a new blueprint with it from scratch, validation is ok, but deployment gives an validation error:

tested this with Vamp marathon quickstart 0.8.1

Unexpected in DSL: {"clusters":{"sava":{"services":[{"routing":{"weight":50,"filters":[]}},{"routing":{"weight":50,"filters":[]}}]}},"endpoints":{"port":"9050"}}

```
---
name: sava:1.0
gateways:
  9050: sava/port
clusters:
  sava:
    routing:
      routes:
        sava:1.0.0:
          weight: 50  # weight in percentage
        sava:1.1.0:
          weight: 50
    services: # services is now a list of breeds
      -
        breed:
          name: sava:1.0.0
          deployable: magneticio/sava:1.0.0
          ports:
            port: 8080/http
        scale:
          cpu: 0.2
          memory: 256
          instances: 1
      -
        breed:
          name: sava:1.1.0 # a new version of our service
          deployable: magneticio/sava:1.1.0
          ports:
            port: 8080/http
        scale:
          cpu: 0.2
          memory: 256
          instances: 1
```
