### ISSUE TITLE
Route weights and filter strengths

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#526]
Each gateway has routes, each route has a weight and optionally filters.
Let's have something like this:

```     
            ---- A, weight: 60%
request ---| --- B, weight: 40%
            ---- C, weight: 30% and user-agent = Firefox
```
A and B don't have filters - total weight of no-filter routes must be 100% which is the case here.
C has a filter and weight.
If request user-agent is Firefox, request either goes to C (30%) or to A or B (70%).
Any request that goes to A or B, goes 60% to A and 40% B including requests that match C filter but are not handled by C (100% - 30% = 70%).

In short, all **other** routes (routes without filters) are in one group, and filter routes in another.
If filter is matched but not handled (weight less than 100%) then it's send to **others** distributed by their weight.

**weight** is used in different context here - single route (filter) or in the group (no filters).

How to specify send all to B if Firefox, otherwise 50% to A and 50% to B?

```yaml
A:
  weight: 50%
  filters: 
  - user-agent != Firefox # filter here, not on B, and it's a negation

B:
  weight: 100%
```
This solution may look counter-intuitive (**not** condition in A).
Another solution would be:

```yaml
A:
  weight: 50%
B:
  weight: 50%
  filter_strength: 50%
  filters: 
  - user-agent == Firefox
```

In this proposal all **weight** properties are related to **other** routes, routes without filter match, and total sum must be always 100%.
**filter_strength** is explicit weight only for filter in the range 0% (never apply) to 100% (always apply).

If we want to send only (and all) Firefox users to B:
```yaml
A:
  weight: 100%
B:
  weight: 0%
  filter_strength: 100%
  filters: 
  - user-agent == Firefox
```
