### ISSUE TITLE
Workflow job scale

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#539]
Custom scale for workflow jobs:

```yaml
name: logger-schedule
script: vamp.log("hi")
scale:
  cpu: 0.5
  memory: 512MB
```

Support for scale reference as well.
Number of instances must be 1 (validate).
