### ISSUE TITLE
Support custom Docker container command line arguments

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#542]
It is possible to specify custom command line arguments for docker containers: https://mesosphere.github.io/marathon/docs/rest-api.html#apps
```json
"parameters": [
  { "key": "a-docker-option", "value": "xxx" },
  { "key": "b-docker-option", "value": "yyy" }
  { "key": "label", "value": "com.example.group=\"webservers1\"" }
  { "key": "label", "value": "com.example.group=\"webservers2\"" }
  { "key": "security-opt", "value": "seccomp:unconfined" }
]
```  

This should be supported in `docker-driver` as well.
It should be on breed and service level - concatenation of breed/service argument lists.

```yaml
services:
  - 
    breed:
      name: ...
      deployable: ...
      ports: ...
      environment_variables: ...
      arguments: ... # breed level
    arguments: ...   # service level
```
Also, Vamp configuration should allow default lines added to all (e.g. for `seccomp` profile).

**Comment by dragoslav** [comment]
configuration example:
```yaml
vamp.operation.deployment.arguments: [ # by default it's an empty list
  "label=vamp",
  "security-opt=seccomp:unconfined"
]
```
Blueprint example:
```yaml
name: sava:1.0

gateways:
  9050: sava/port

clusters:

  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 8080/http
        environment_variables:
          debug[SAVA_DEBUG]: true
        arguments:
          label: breed

      arguments:
        label: service
```

Resolved to Marathon:
```json
"parameters": [
  {
    "key": "label",
    "value": "vamp"
  },
  {
    "key": "security-opt",
    "value": "seccomp:unconfined"
  },
  {
    "key": "label",
    "value": "breed"
  },
  {
    "key": "label",
    "value": "service"
  }
]
```
