### ISSUE TITLE
Reverting TCP port to HTTP

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#545]
Even though internal gateway port is created as TCP (in case of breed TCP port), later during gateway synchronization it's reverted to HTTP. 
Example blueprint:
```yaml
name: wordpress:1.3
gateways:
  '9081': wordpress/port
clusters:
  wordpress:
    services:
      - breed:
          name: wordpress:1.3
          deployable: docker://wordpress:4-apache
          ports:
            port: 80/http
          dependencies:
            backend: mariadb:1.1
          environment_variables:
            WORDPRESS_DB_HOST: $backend.host:$backend.ports.mysql
            WORDPRESS_DB_PASSWORD: abc
        scale:
          cpu: 0.5
          memory: 400MB
          instances: 1
  backend:
    services:
      - breed:
          name: mariadb:1.1
          deployable: docker://mariadb:10
          ports:
            mysql: 3306/tcp
          environment_variables:
            MYSQL_ROOT_PASSWORD: abc
        scale:
          cpu: 1
          memory: 400MB
          instances: 1
```
