### ISSUE TITLE
Investigate potential bug: multiple gateways with the same port

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#554]
```yaml
name: wordpress:1.3
gateways:
  '9081': wordpress/port
clusters:
  wordpress:
    services:
      - breed:
          name: wordpress:1.3
          deployable: docker://wordpress:4-apache
          ports:
            port: 80/http
          dependencies:
            backend: mariadb:1.1
          environment_variables:
            WORDPRESS_DB_HOST: $backend.host:$backend.ports.mysql
            WORDPRESS_DB_PASSWORD: abc
        scale:
          cpu: 0.5
          memory: 400MB
          instances: 1
  backend:
    services:
      - breed:
          name: mariadb:1.1
          deployable: docker://mariadb:10
          ports:
            mysql: 3306/tcp
          environment_variables:
            MYSQL_ROOT_PASSWORD: abc
        scale:
          cpu: 1
          memory: 400MB
          instances: 1
```

Caused after few deployments/undeployments:
```json
[
  {
    "name": "dd6599e4-25af-4314-ab9e-6a4e06e1425d/backend/mysql",
    "lookup_name": "1863a57c3aea4395af76c0334603a9135e27e738",
    "port": "40000/tcp",
    "deployed": true,
    "sticky": "none",
    "routes": {
      "dd6599e4-25af-4314-ab9e-6a4e06e1425d/backend/mariadb:1.1/mysql": {
        "weight": "100%",
        "filters": [],
        "rewrites": [],
        "instances": [
          {
            "name": "dd6599e4-25af-4314-ab9e-6a4e06e1425d_2394104e68c1e63b1821.efc4ff45-da03-11e5-a07e-024214d6c6d8",
            "host": "localhost",
            "port": 31448
          }
        ]
      }
    }
  },
  {
    "name": "d1a6b648-c844-4ab1-9cb4-826d714755bc/9081",
    "lookup_name": "7ef045bb74df3a3e06f1a4918fe946bdd2708dbe",
    "port": "9081",
    "deployed": false,
    "sticky": "none",
    "routes": {
      "d1a6b648-c844-4ab1-9cb4-826d714755bc/wordpress/port": {
        "weight": "100%",
        "filters": [],
        "rewrites": []
      }
    }
  },
  {
    "name": "dd6599e4-25af-4314-ab9e-6a4e06e1425d/9055",
    "lookup_name": "3e5f043d78f2147ce248a87f97370906133938f0",
    "port": "9055",
    "deployed": true,
    "sticky": "none",
    "routes": {
      "dd6599e4-25af-4314-ab9e-6a4e06e1425d/wordpress/port": {
        "weight": "100%",
        "filters": [],
        "rewrites": [],
        "instances": [
          {
            "name": "dd6599e4-25af-4314-ab9e-6a4e06e1425d/wordpress/port",
            "host": "localhost",
            "port": 40001
          }
        ]
      }
    }
  },
  {
    "name": "078184b5-7571-44ca-a089-0a8062d67998/9055",
    "lookup_name": "189bbe0cf6dae4266075378b2f64353a9e0c6d3e",
    "port": "9055",
    "deployed": false,
    "sticky": "none",
    "routes": {
      "078184b5-7571-44ca-a089-0a8062d67998/wordpress/port": {
        "weight": "100%",
        "filters": [],
        "rewrites": []
      }
    }
  },
  {
    "name": "ea537d4c-a77e-46e1-81c4-bb4fc9524d27/9055",
    "lookup_name": "730c39064fea07dfd70496664a800487e51e8970",
    "port": "9055",
    "deployed": false,
    "sticky": "none",
    "routes": {
      "ea537d4c-a77e-46e1-81c4-bb4fc9524d27/wordpress/port": {
        "weight": "100%",
        "filters": [],
        "rewrites": []
      }
    }
  },
  {
    "name": "28cb3110-4eb3-4348-9cb1-19bedd6889e1/9081",
    "lookup_name": "aabb43c098d20217f216f1919edf2762997015d6",
    "port": "9081",
    "deployed": false,
    "sticky": "none",
    "routes": {
      "28cb3110-4eb3-4348-9cb1-19bedd6889e1/wordpress/port": {
        "weight": "100%",
        "filters": [],
        "rewrites": []
      }
    }
  },
  {
    "name": "9b4a3f01-8e9e-4cc8-8b2d-abd38c24f37a/9050",
    "lookup_name": "8b293396dd6eedc1e5b92085b3b219929c52ffb5",
    "port": "9050",
    "deployed": false,
    "sticky": "none",
    "routes": {
      "9b4a3f01-8e9e-4cc8-8b2d-abd38c24f37a/sava/port": {
        "weight": "100%",
        "filters": [],
        "rewrites": []
      }
    }
  },
  {
    "name": "6eff625b-989d-4244-ba97-a4542bb85e39/9081",
    "lookup_name": "5d704dbd27b546638057aa45aad2ff6c37238cb7",
    "port": "9081",
    "deployed": false,
    "sticky": "none",
    "routes": {
      "6eff625b-989d-4244-ba97-a4542bb85e39/wordpress/port": {
        "weight": "100%",
        "filters": [],
        "rewrites": []
      }
    }
  },
  {
    "name": "dd6599e4-25af-4314-ab9e-6a4e06e1425d/wordpress/port",
    "lookup_name": "5b9f39a85996ae2c1cb5be151b939519688410b4",
    "port": "40001/http",
    "deployed": false,
    "sticky": "none",
    "routes": {
      "dd6599e4-25af-4314-ab9e-6a4e06e1425d/wordpress/wordpress:1.3/port": {
        "weight": "100%",
        "filters": [],
        "rewrites": [],
        "instances": [
          {
            "name": "dd6599e4-25af-4314-ab9e-6a4e06e1425d_761a888d062c09010d5b.594ada2b-da04-11e5-a07e-024214d6c6d8",
            "host": "localhost",
            "port": 31446
          }
        ]
      }
    }
  }
]
```
