### ISSUE TITLE
When using filtered routes, the slider 'Combined' value flips out when changing any value

### ISSUE THREAD

**Issue by basbl** [magneticio/vamp#568]
Given the following blueprint

```
---
name: project
gateways:
  9065: service/port
clusters:
  service:
    routing:
      routes:
        breed-a-1:
          weight: 50%
        breed-b-1:
          weight: 50%
        breed-c-1:
          weight: 100%
          filters:
            - condition: "{ hdr_ip(x-forwarded-for) xxx.xxx.xxx.xxx }"
    services:
# rest of blueprint ...
```

When trying to change the weight of either of the routes the GUI flips out to values far beyond the maximum value of 100. When sliding the filtered routes to 0, then back up, the combined value stops flipping out, but you can't save.

This issue is present while using any kind of filtering.
