### ISSUE TITLE
Premature gateway update

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#570]
It's possible to update gateways before all services are deployed, e.g.:
```yaml
name: sava:1.0
gateways:
  9050: sava/port
clusters:
  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 8080/http
```
Once it's running, update it with: 

```yaml
name: sava:1.0
clusters:
  sava:
    routing:
      routes:
        sava:1.0.0:
          weight: 50%  # weight in percentage
        sava:1.1.0:
          weight: 50%
    services: # services is now a list of breeds
      -
        breed:
          name: sava:1.0.0
          deployable: magneticio/sava:1.0.0
          ports:
            port: 8080/http
        scale:
          cpu: 0.2
          memory: 64MB
          instances: 1
      -
        breed:
          name: sava:1.1.0 # a new version of our service
          deployable: magneticio/sava:1.1.0
          ports:
            port: 8080/http
```

Inner cluster gateway with 50% split will be created even `sava:1.1.0` is not yet deployed.
