### ISSUE TITLE
Orphan gateways

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#573]
At the moment we replace a gateway during new gateway create request (remove old and add new one) if ports are equal.

For instance if we deploy:
```yaml
name: sava:1.0
gateways:
  9050: sava/port
clusters:
  sava:
    services:
      breed: sava:1.0.0
```
Then undeploy and deploy again with different name (UUID), old gateway 9050 will be silently removed and new one would be created.
Current UI doesn't support gateway actions and clean up.

Possibility:
1) if gateway (port) exist, respond with validation error.
2) keep it like it is, silently replace the gateway

Solution 1) is less error prone and gateways are presented as first-class citizens as they should be (next to deployments).

This also may be related to #500 and #492
