### ISSUE TITLE
Service level environment variables are not interpolated

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#576]
If there are no service level environment variables, then breed variables are interpolated, otherwise none of them.
Example blueprint:
```yaml
name: runner

gateways:
  9053: frontend/port

clusters:
  frontend:
    services:
      breed:
        name: frontend
        deployable: magneticio/sava_runner:1.0.0
        ports:
          port: 8081/http
        environment_variables:
          SAVA_RUNNER_ID: frontend
          # not interpolated:
          SAVA_RUNNER_HTTP_DEPENDENCY_URL1: http://$backend.host:$backend.ports.port
        dependencies:
          backend: backend

      environment_variables:
        SAVA_RUNNER_ID: frontend
        # not interpolated:
        SAVA_RUNNER_HTTP_DEPENDENCY_URL1: http://$backend.host:$backend.ports.port

  backend:
    services:
      breed:
        name: backend
        deployable: magneticio/sava_runner:1.0.0
        ports:
          port: 8085/http
        environment_variables:
          SAVA_RUNNER_ID: backend
          SAVA_RUNNER_HTTP_PORT1: 8085
```
