### ISSUE TITLE
It's not possible to use dependency name mapping

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#577]
Instead to use a symbolic (mapped) name in interpolation strings, only the full dependency name is supported.
For instance in this example `backend` can't be used, but `runner:1.0.0` (breed name):

```yaml
name: runner

gateways:
  9053: frontend/port

clusters:
  frontend:
    services:
      breed:
        name: frontend
        deployable: magneticio/sava_runner:1.0.0
        ports:
          port: 8081/http
        environment_variables:
          SAVA_RUNNER_ID: frontend          # used mapped dependency name:
          SAVA_RUNNER_HTTP_DEPENDENCY_URL1: http://$be.host:$be.ports.port
        dependencies:
          # mapped dependency breed name "runner:1.0.0" to "be"
          be: runner:1.0.0

  backend:
    services:
      breed:
        name: runner:1.0.0 # dependency name
        deployable: magneticio/sava_runner:1.0.0
        ports:
          port: 8085/http
        environment_variables:
          SAVA_RUNNER_ID: backend
          SAVA_RUNNER_HTTP_PORT1: 8085
```
