### ISSUE TITLE
Using reference scale causes validation errors

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#586]
scale:
```yaml
name: small
instances: 1
memory: 64MB
cpu: 0.1
```
blueprint:
```yaml
clusters:
  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 8080/http
        environment_variables:
          debug[SAVA_DEBUG]: true
    
      scale: small
```
Will cause validation error on every deployment read:
```json
{
    "message": "The request content was malformed. Either it should be a reference 'scale -> small' or an anonymous inline definition, but not both."
}
```
