### ISSUE TITLE
Have service-discovery based on virtual hosts

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#589]
Users want to be able to use virtual hosts / DNS names instead of ports.

**Comment by dragoslav** [comment]
`PUT ${VAMP_URL}/api/v1/deployments/runner`
```yaml
name: runner

gateways:
  9050: runner1/port
  9060: runner2/port
  
clusters:
  runner1:
    services:
      breed:
        name: http:1.0.0
        deployable: magneticio/sava:runner_1.0
        ports:
          port: 8081/http
        environment_variables:
          SAVA_RUNNER_ID: 1.0.0
  runner2:
    services:
      breed:
        name: http:2.0.0
        deployable: magneticio/sava:runner_1.0
        ports:
          port: 8081/http
        environment_variables:
          SAVA_RUNNER_ID: 2.0.0
``` 

HAProxy (VGA) listens on port 80.
In order to test virtual hosts without setting up the DNS (just for this specific deployment), append 
```
192.168.99.100 9050.runner.vamp 9060.runner.vamp 
192.168.99.100 port.runner1.runner.vamp port.runner2.runner.vamp
```
 to `/etc/hosts` file. Replace `192.168.99.100` with your HAProxy IP if needed.

Check in browser:
- `http://9050.runner.vamp`
- `http://9060.runner.vamp`
- `http://port.runner1.runner.vamp `
- `http://port.runner2.runner.vamp `

Virtual hosts are created based on gateway names (reversing, and using `.` instead of `/`) and adding a custom configurable domain (by default vamp).
For inner (cluster) gateways it is then always like: `port_name.cluster_name.deployment_name.custom_domain`
For example if gateway name is `runner/9050` then virtual host for default domain becomes `9050.runner.vamp`
