### ISSUE TITLE
Tutorial works?

### ISSUE THREAD

**Issue by gianarb** [magneticio/vamp#593]
Hello

Thanks for this project! it seems awesome! 
I am following your tutorial and in the second step, during the canary deploy I have this error when I past your spec
http://vamp.io/documentation/guides/getting-started-tutorial/2-canary-release/
```
The request content was malformed. Can't find any value for path: /deployable
```

am I doing something wrong?
Thanks

**Comment by olafmol** [comment]
Tnx @gianarb for your kind words! What version of VAMP are you using, what version of Docker and on what OS? Can you past the exact blueprint or deployment you are posting to VAMP? tnx!

**Comment by gianarb** [comment]
Yes I am only following the official tutorial..
I am using osx 10.11 (el capitano)
```
ga:~ gianarb$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64
```
About vamp I think the latest because I used this command
```
docker run --net=host \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v $(which docker):/bin/docker \
           -v "/sys/fs/cgroup:/sys/fs/cgroup" \
           -e "DOCKER_HOST_IP=`docker-machine ip default`" \
           magneticio/vamp-docker:0.8.4-marathon
```
the exact blueprint is 
```
---
name: sava:1.0
gateways:
  9050: sava/port
clusters:
  sava:
    routing:
      routes:
        sava:1.0.0:
          weight: 50%  # weight in percentage
        sava:1.1.0:
          weight: 50%
    services: # services is now a list of breeds
      -
        breed:
          name: sava:1.0.0
          deployable: magneticio/sava:1.0.0
          ports:
            port: 8080/http
        scale:
          cpu: 0.2
          memory: 64MB
          instances: 1
      -
        breed:
          name: sava:1.1.0 # a new version of our service
          deployable: magneticio/sava:1.1.0
          ports:
            port: 8080/http
        scale:
          cpu: 0.2
          memory: 64MB
          instances: 1
```

Thanks a lot
