### ISSUE TITLE
Using filter reference is broken

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#594]
```yaml
name: runner
port: 9060
routes:
  route-weight-filter-strength-1/9058:
    weight: 80%
  route-weight-filter-strength-2/9059:
    weight: 20%
    filter_strength: 50%
    filters: 
    - url2
```
