### ISSUE TITLE
Document how to split up blueprints/deployments and how to connect these together

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#603]
Background: To create a repeatable proces/workflow it’s important that people understand how to split up a blueprint/deployment YAML into separate parts that are corresponding to the different (micro)services they are deploying, and also to understand how VAMP connects these different parts (blueprints/deployments) together so they can talk to each other.

We need to describe how one can move from 1 blueprint/deployment that controls all deployables to multiple blueprints/deployments and how these can connect to each other, using f.e. service-discovery.

**Comment by treaz** [comment]
I have a use case and I think that it is related to this issue.
I've been reading about VAMP [service-discovery and dependencies](http://vamp.io/documentation/about-vamp/service-discovery/).

According to the documentation, the dependency is described in the same blueprint.
```yaml
name: my_blueprint:1.0
clusters:
  my_frontend_cluster:
    services:
      breed:
        name: my_frontend_service:0.1
        deployable: docker://company/frontend:0.1
        ports:
          port: 8080/http
        dependencies:
          backend: my_backend_service:0.3
        environment_variables:
         BACKEND_HOST: $backend.host
         BACKEND_PORT: $backend.ports.jdbc
      scale:
        instances: 3         
  my_backend_cluster:
    services:
      breed:
        name: my_backend_service:0.3
        deployable: docker://company/backend:0.3
        ports:
          jdbc: 8080/tcp
      scale:
        instances: 4
```

I'd like to have 2 separate blueprints, in which one of them references the other. Something like below.
```yaml
name: my_backend:1.0
clusters:     
  my_backend_cluster:
    services:
      breed:
        name: my_backend_service:0.3
        deployable: docker://company/backend:0.3
        ports:
          jdbc: 8080/tcp
      scale:
        cpu: 1.0
        memory: 512.0MB
        instances: 4
```

```yaml
name: my_frontend:1.0
clusters:
  my_frontend_cluster:
    services:
      breed:
        name: my_frontend_service:0.1
        deployable: docker://company/frontend:0.1
        ports:
          port: 8080/http
        dependencies:
          backend: my_backend_service:0.3
        environment_variables:
         BACKEND_HOST: $backend.host
         BACKEND_PORT: $backend.ports.jdbc
      scale:
        cpu: 1.0
        memory: 512.0MB
        instances: 3 
```

I created & saved the _my_backend:1.0_ blueprint. When I tried to save the _my_frontend:1.0_ blueprint, I got `Unresolved breed dependency for breed 'my_frontend_service:0.1' and dependency 'backend -> my_backend_service:0.3'.`

Am I doing something wrong? Is this currently possible with VAMP?

**Comment by dragoslav** [comment]
We may introduce that later, but now that's not possible. All dependencies need to be resolved within the same blueprint/deployment. You could for instance add your breeds (scale etc.) separately and have blueprint as:
```yaml
name: my_blueprint:1.0
clusters:
  my_frontend_cluster:
    services:
      breed: my_frontend_service:0.1
      scale: medium     
  my_backend_cluster:
    services:
      breed: my_backend_service:0.3
      scale: medium
```
All references need to be defined before actual deployment but not when blueprint is created.
