### ISSUE TITLE
mongoDB deployment not running on specified gateway port

### ISSUE THREAD

**Issue by treaz** [magneticio/vamp#606]
Using vamp.io version 0.8.4
I'm trying to run a mongoDB deployment on vamp.io and I don't understand why it's not available on the port that I've specified in the gateway section of the blueprint.

First of all, I've defined a new **breed**
```yaml
name: mongo:latest
deployable: docker://mongo:latest
ports:
  port: 27017/http
environment_variables: {}
constants: {}
arguments: []
dependencies: {}
```

According to the [dockerfile](https://github.com/docker-library/mongo/blob/191cc63288fb44c2fd147eac27ade07ae4b6b0b5/3.2/Dockerfile), 27017 is the port that is exposed to docker containers.

Then I created the following **blueprint** and deployed it
```yaml
name: mongo:latest
gateways:
  '27017':
    sticky: none
    routes:
      mongo/port:
        weight: null
        filters: []
        rewrites: []
clusters:
  mongo:
    services:
    - breed:
        name: mongo:latest
        deployable: docker://mongo:latest
        ports:
          port: 27017/http
        environment_variables: {}
        constants: {}
        arguments: []
        dependencies: {}
      environment_variables: {}
      scale:
        cpu: 0.2
        memory: 64.0MB
        instances: 1
      arguments: []
      dialects: {}
    routing: {}
    dialects: {}
environment_variables: {}
```

Deployment was successful.

Note: 192.168.99.100 is the ip of the machine that is hosting my vamp instance.
In the deployment details screen there is a server and a port 192.168.99.100:31114 on which mongoDB _can be reached_ with the mongo cli client.
However, on 192.168.99.100:27017 mongoDB _cannot be reached_ with the mongo cli client.

I couldn't find anything about this in the docs. What am I missing here?

**Comment by olafmol** [comment]
Hi! Can you deploy the mongoDB docker container without VAMP, and access it at it's default port?

**Comment by treaz** [comment]
Yes.
`docker run -P --name some-mongo -d mongo` results in a container running mongo
`1d074805bee3        mongo                                   "/entrypoint.sh mongo"   4 minutes ago       Up 5 seconds        0.0.0.0:32770->27017/tcp   some-mongo`

**Comment by olafmol** [comment]
What happens if you only deploy the blueprint? It's not necessary to create a separate breed upfront (BTW, you can reset all deployments in VAMP using 192.168.99.100:8080/api/v1/reset)

**Comment by treaz** [comment]
As I was saying before, the container runs well. And there is a mongo instance that is exposed on an obscurce port (~30000 something).
The issue is that on port 27017 there's nothing listening

**Comment by olafmol** [comment]
@treaz can you start from scratch with a clean quickstart install and only deploy the blueprint part and see what happens? (NB i cannot reproduce it, on my dev machine your blueprint works fine, the obscure port is because mesos assigns random ports to running containers, and VAMP should be able to connect this mesos-assigned port to the port you defined in the gateway, like 27017)

**Comment by dragoslav** [comment]
I just get: "It looks like you are trying to access MongoDB over HTTP on the native driver port." for both 27017 and in my case port 31444. If you need just TCP without HTTP you should set port as `27017/tcp`

**Comment by treaz** [comment]
Thank you for the responses until now.
I've updated the blueprint to use port 27017 TCP (instead of HTTP).
I've also started a fresh vamp container (stopped all running docker containers, removed all of them and followed the steps described in quick_start).

None of these attempts make any difference. I forgot to mention before that I can telnet to port 27017, but I can't connect with the mongo client

Here's the output of docker ps:
```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED              STATUS              PORTS                      NAMES
a05a66911fc0        mongo:latest                            "/entrypoint.sh mongo"   About a minute ago   Up About a minute   0.0.0.0:31270->27017/tcp   mesos-0d742e94-ccba-4a5f-8650-f42205d55208-S0.07b8cd24-40b1-466b-bda1-cc9cbcd2c9e6
400194d0defb        magneticio/vamp-docker:0.8.4-marathon   "supervisord -n -c /e"   5 minutes ago        Up 5 minutes                                   compassionate_carson
```

If I do `mongo 192.168.99.100:31270` I can connect to mongoDB.
If I do `mongo 192.168.99.100:27017` I cannot connect to mongoDB

I guess the issue is in the VGA, but I'm clueless about how to debug that...

**Comment by dragoslav** [comment]
Ok, it may be something with our default HAProxy configuration for TCP. We'll investigate.

**Comment by dragoslav** [comment]
Hi @treaz could you try also `magneticio/vamp-docker:develop` instead of `magneticio/vamp-docker:0.8.4-marathon`? I did some checks, also tried to use different balance algorithm (http://comments.gmane.org/gmane.comp.db.mongodb.user/61077 and http://comments.gmane.org/gmane.comp.db.mongodb.user/61077) and found one issue that is just fixed https://github.com/magneticio/vamp/issues/609
`develop` contains the code from `develop` branch and we are close to make a new release.
For instance this is the output I get:
```bash
$ mongo 192.168.99.100:27017
MongoDB shell version: 3.2.4
connecting to: 192.168.99.100:27017/test
Server has startup warnings: 
2016-04-16T20:17:28.214+0000 I CONTROL  [initandlisten] 
2016-04-16T20:17:28.219+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2016-04-16T20:17:28.220+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-04-16T20:17:28.220+0000 I CONTROL  [initandlisten] 
2016-04-16T20:17:28.220+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2016-04-16T20:17:28.220+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-04-16T20:17:28.220+0000 I CONTROL  [initandlisten] 
> 
```

**Comment by treaz** [comment]
@dragoslav, I just tried it and it still doesn't work.
```yaml
name: mongo:latest
gateways:
  27017: mongo/port
clusters:
  mongo:
    services:
      breed:
        name: mongo:latest
        deployable: mongo:latest
        ports:
          port: 27017/tcp
      scale:
        cpu: 0.6
        memory: 512MB
        instances: 1
```

```bash
docker run --net=host \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v $(which docker):/bin/docker \
           -v "/sys/fs/cgroup:/sys/fs/cgroup" \
           -e "DOCKER_HOST_IP=`docker-machine ip default`" \
           magneticio/vamp-docker:develop
```

```
mongo 192.168.99.100:31826
MongoDB shell version: 3.0.7
connecting to: 192.168.99.100:31826/test
Server has startup warnings:
2016-04-16T22:45:54.693+0000 I CONTROL  [initandlisten]
2016-04-16T22:45:54.693+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2016-04-16T22:45:54.694+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-04-16T22:45:54.694+0000 I CONTROL  [initandlisten]
2016-04-16T22:45:54.694+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2016-04-16T22:45:54.694+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-04-16T22:45:54.694+0000 I CONTROL  [initandlisten]
>
```

```
mongo 192.168.99.100:27017
MongoDB shell version: 3.0.7
connecting to: 192.168.99.100:27017/test
2016-04-17T00:46:44.341+0200 I NETWORK  recv(): message len 1347703880 is invalid. Min 16 Max: 48000000
2016-04-17T00:46:44.341+0200 I NETWORK  DBClientCursor::init call() failed
2016-04-17T00:46:44.344+0200 E QUERY    Error: DBClientBase::findN: transport error: 192.168.99.100:27017 ns: admin.$cmd query: { whatsmyuri: 1 }
    at connect (src/mongo/shell/mongo.js:181:14)
    at (connect):1:6 at src/mongo/shell/mongo.js:181
exception: connect failed
```

**Comment by dragoslav** [comment]
and with gateway port 27017 as TCP?

```yaml
name: mongo:latest
gateways:
  27017/tcp: mongo/port
clusters:
  mongo:
    services:
      breed:
        name: mongo:latest
        deployable: mongo:latest
        ports:
          port: 27017/tcp
      scale:
        cpu: 0.6
        memory: 512MB
        instances: 1
```
