### ISSUE TITLE
Reseting port type to HTTP

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#609]
If for inner (cluster) gateway routes are specified arguments (e.g. weight, balance...) then port type is reset to HTTP.  

```yaml
name: mongo:latest
gateways:
  '27017/tcp':
    routes:
      mongo/port:
        balance: source
clusters:
  mongo:
    services:
    - breed:
        name: mongo:latest
        deployable: docker://mongo:latest
        ports:
          port: 27017/tcp
      scale:
        cpu: 0.2
        memory: 64.0MB
        instances: 1
    routing:
      port:
        routes:
          mongo:latest:
            balance: source
```
will result in: 
```yaml
- name: mongo/27017
  lookup_name: 498f8a3e5d03b7152994d0ee3dcf6e53e5d9d4f2
  port: 27017/tcp
  deployed: true
  sticky: none
  routes:
    mongo/mongo/port:
      weight: 100%
      balance: source
      filter_strength: 0%
      filters: []
      rewrites: []
      instances:
      - name: mongo/mongo/port
        host: localhost
        port: 40000
- name: mongo/mongo/port
  lookup_name: 96fb310cb8e1bdf3925e1e8aada2cb1037c3bb1c
  port: 40000/http
  deployed: true
  sticky: none
  routes:
    mongo/mongo/mongo:latest/port:
      weight: 100%
      balance: source
      filter_strength: 0%
      filters: []
      rewrites: []
      instances:
      - name: mongo_mongo-latest-308a4f711bb5758285b8.13934e8e-0365-11e6-a3b1-0242d2929ab2
        host: 192.168.99.100
        port: 31805
```
Note that port 40000 is HTTP for `mongo/mongo/port`  while breed port is TCP.
There is no bug if inner gateway routes are not specified.
