### ISSUE TITLE
Allow virtual hosts for services

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#610]
This can be useful for service discovery in general.
```yaml
name: deployment
clusters:
  cluster:
    services:
      - breed: service1 # has ports 'web' and 'health'
      - breed: service2 # has ports 'web' and 'health'
```
Right now it will be created:
- `web.cluster.deployment`
- `health.cluster.deployment`

In addition we can add also:
- `web.service1.cluster.deployment`
- `web.service2.cluster.deployment`
- `health.service1.cluster.deployment`
- `health.service2.cluster.deployment`
