### ISSUE TITLE
Add support for custom virtual hosts

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#611]
For each gateway instead of predefined name based virtual host, it should be possible to specify the overrides.

```yaml
name: location
port: 8050/http
virtual_hosts: [
  "location.api.service",
  "whereami.com"
]
```
