### ISSUE TITLE
PUT-ing a blueprint to an existing deployment triggers database constraint errors

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#62]
If you deploy this

```yaml
name: sava:1.0

endpoints:
  sava.port: 9050

clusters:

  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 80/http
```

and then PUT the following to the running deployment:

```yaml

name: sava:1.0

endpoints:
  sava.port: 9050

clusters:

  sava:
    services: # services is now a list of breeds
      -
        breed:
          name: sava:1.0.0
          deployable: magneticio/sava:1.0.0
          ports:
            port: 80/http           
      -
        breed:
          name: sava:1.1.0 # a new version of our service
          deployable: magneticio/sava:1.1.0
          ports:
            port: 80/http
```

you get

```json
{
    "message": "The request content was malformed. Unsupported deployment request. Reason: PersistenceOperationFailure(org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: \"idx_deployment_hosts ON PUBLIC.\"\"deployment_hosts\"\"(\"\"name\"\", \"\"breed_id\"\")\"; SQL statement:\ninsert into \"deployment_hosts\" (\"name\",\"host_value\",\"breed_id\")  values (?,?,?) [23505-166])"
}
```
