### ISSUE TITLE
Detecting Chrome on Mac does not work for filter conditions

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#622]
It seems Chrome on Mac also has "Safari" in it's user-agent string:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

Our shortcode does seem to parse this only partially, so the workaround for now is to use: 

condition: User-Agent = Safari AND User-Agent = Chrome

We need to find a better/more elegant way to handle this.

**Comment by dragoslav** [comment]
Based on user agent strings, if I understand this correctly the problem is if you specify something like this `User-Agent = Safari` and expect only Safari, but also Chrome will be matched?
Does `User-Agent = Chrome` still match correctly Chrome?

**Comment by dragoslav** [comment]
Following substitutions are implemented, based on http://www.useragentstring.com/pages/useragentstring.php:
```yaml
Chrome  : "< hdr_sub(user-agent) Chrome >"
Firefox : "< hdr_sub(user-agent) Firefox >"
Safari  : "< hdr_sub(user-agent) Safari > and < hdr_sub(user-agent) Version >"
Edge    : "< hdr_sub(user-agent) Edge >"
IE      : "< hdr_sub(user-agent) MSIE >"
```
