### ISSUE TITLE
Escalation "to_all" doesn't work for combination of scale changes

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#624]
```yaml
---
name: sava

gateways:
  9050: sava/port

clusters:

  sava:
    breed:
      name: sava:1.0.0
      deployable: docker://magneticio/sava:1.0.0
      ports:
        port: 8080

    scale:
      cpu: 0.1
      memory: 128MB
      instances: 1

    sla:
      type: response_time_sliding_window
      threshold:
        upper: 1000
        lower: 100
      window:
        interval: 5
        cooldown: 0

      escalations:
      - type: to_all
        escalations:
        - type: scale_memory
          minimum: 128.0
          maximum: 256.0
          scale_by: 16.0
        - type: scale_cpu
          minimum: 0.1
          maximum: 4.0
          scale_by: 0.2
```

Only `scale_memory` is executed and after it reaches its limit (e.g. maximum) then `scale_cpu` is executed.
`to_all` should be applied to all of them in parallel.
