### ISSUE TITLE
Using the same routes may avoid proper gateway validation

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#648]
```yaml
name: 9050
port: 9050/http
routes:
  "[192.168.99.100:5050]":
    weight: 50%
  "[192.168.99.100:5050]":
    weight: 50%
```

Results in:
```yaml
name: '9050'
lookup_name: b435ff580395ac9e95606e9199ce27d163966a4e
port: 9050/http
deployed: false
sticky: none
virtual_hosts: []
routes:
  '[192.168.99.100:5050]':
    weight: 50%
    balance: default
    filter_strength: 0%
    filters: []
    rewrites: []
```

Instead of validation error - total weight is 50%.
