### ISSUE TITLE
Resource check (cpu, memory) should be configurable

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#659]
While number of instances are important and Vamp should track them, resources like CPU, memory etc. may or may not be supported by underlying container engine. Even worse they can be interpreted differently (e.g. CPU shares). It should be possible to configure Vamp that it should validate used resources or not:
```yaml
check {
  cpu: false
  memory: true
  instances: true
}
```
