### ISSUE TITLE
Default virtual hosts should be added to get gateway(s) response (serialisation)

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#664]
If no custom virtual hosts are set but virtual host generation is enabled then:
```yaml
name: ...
port: ...
virtual_hosts: []
```

`virtual_hosts` should contain generated value.
