### ISSUE TITLE
Vamp OpenAPI specification

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#673]
Not really an issue but wanted to share the following. As a pet project I started writing an openapi (formerly known as swagger) specification of the Vamp API. The resulting Yaml can be found here: [https://github.com/JoshFalken/VampOpenApiGenerator/blob/master/VampGenerator/vampopenapi.yaml](https://github.com/JoshFalken/VampOpenApiGenerator/blob/master/VampGenerator/vampopenapi.yaml). Some findings during the writing of this API:

- [Issue 638](https://github.com/magneticio/vamp/issues/638) which blocks the usability of generated C# code. JSON.NET doesn't support arrays in this format.
- The breed/breedref construction isn't supported by the openAPI specification. You either specify usage of the full breed format or the breedref format. There is no room for both in the specification. 
- The API is very consistent in its naming, it's possible to generate the specification from a number of stubs. I think this is very good.
- It is hard to extract the data types from the docs. A seperate part of the documentation which specifies the formats helps to 

Just a note: because of issue 638 I did not yet test whether or not the whole specification is correct. It is however a lot of fun to paste the specification in [http://editor.swagger.io](http://editor.swagger.io) and click around.

**Comment by dragoslav** [comment]
Thanks @JoshFalken, some time ago also tried to do something similar and indeed full breed + breed ref isn't supported. https://github.com/magneticio/vamp/issues/684 should help also in this case. It will be interesting to see if we can support pattern `full artifact` and `artifact ref` in a nice way.

**Comment by JoshFalken** [comment]
I don't know whether or not Vamp supports an object that includes both ref and all the other properties and filters accordingly. What I mean is something like the next object. This is a solution that I also see in other specs. Spec would than become:

```
  Breed:
    type: object
    properties:
      ref:
        type: string
        description: Reference to another breed
      name:
        type: string
        description: The name of the breed
      deployable:
        type: string
        description: Deployables are pointers to the actual artefacts that get deployed. Vamp supports Docker containers or can support any other artefacts supported by your container manager.
      ports:
        type: object
        additionalProperties:
          type: string
      environment_variables:
        type: object
        additionalProperties:
          type: string
      arguments:
        type: object
        additionalProperties:
          type: string
      dependencies:
        type: object
        additionalProperties:
          type: string
      constants:
        type: object
        additionalProperties:
        type: string
```
