### ISSUE TITLE
Configurable HAProxy IP and port for virtual hosts

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#674]
```yaml
vamp.gateway-driver.haproxy.virtual-hosts {
  ip: "127.0.0.1" # VAMP_GATEWAY_DRIVER_HAPROXY_VIRTUAL_HOSTS_IP
  port: 40800     # VAMP_GATEWAY_DRIVER_HAPROXY_VIRTUAL_HOSTS_PORT
}
```
