### ISSUE TITLE
Virtualhost weirdness

### ISSUE THREAD

**Issue by harmw** [magneticio/vamp#688]
I've got the following blueprint loaded in Vamp:
```
name: crowbar
clusters:
  crowbar:
    services:
      breed:
        name: odd-scenario
        deployable: magneticio/sava:1.0.0
        ports:
          entry: 8080/http
        environment_variables:
          SERVICE_NAME: crowbar
      scale:
        cpu: 0.1
        memory: 64MB
        instances: 1
```
This will produce the following vhost in the Vamp haproxy.cfg:
```
[..]
  # destination: crowbar/crowbar/entry
  acl 4b5876404b7360f0 hdr(host) -i entry.crowbar.crowbar.blaze
  use_backend ada682028708a5f19a9a0b6f19791c305530bfab  if 4b5876404b7360f0  
```
The vhost **entry.crowbar.crowbar.blaze** mentioned here doesn't make very much sense on our platform, where we're used to names like **crowbar.blaze**. How should I proceed here?

My expectation is such a name would be handled by a given haproxy _frontend_ behind which all the routing (A/B stuff, canary releasing) takes place. Eg. all our services connect with _crowbar.blaze_, they are not bothered with the Vamp canary-release plans and routing stuff.

**Comment by dragoslav** [comment]
You would need to set it directly:
```yaml
name: sava:1.0
gateways:
  9050: sava/port
clusters:
  sava:
    routing:
      port:
        virtual_hosts: [
          "sava.vamp"
        ]
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 8080/http
```
Each cluster has (implicit) gateway/routing and it's per port name. Virtual hosts can be set for any gateway. Also it's possible to use Gateway API later on to make additional changes.

Anyway, I think it should be more convenient than this, thus https://github.com/magneticio/vamp/issues/689
