### ISSUE TITLE
API endpoint for creation of multiple artifacts in single request

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#698]
It would be handy to import list of artifacts instead of creating one by one using separate files, e.g.:
- loading examples
- easier integration with build pipeline

Similar to something that Kubernetes supports: http://kubernetes.io/docs/user-guide/kubectl-cheatsheet/

`POST /api/v1`
```yaml
-
  name: ...
  kind: breed
  ...
-
  name: ...
  kind: blueprint
  ...
```
In this case we need to have `kind` for each artifact that will be mapped internally to specific endpoint (e.g. breeds, blueprints).

Also `PUT` and `DELETE` requests are supported.
