### ISSUE TITLE
Partial info message

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#706]
A part of full `info` message `/api/v1/info` we should support partial request/response.
Full message consists of:
```yaml
{
    "message": "...",
    "version": "...",
    "uuid": "...",
    "running_since": "...",
    "jvm": {...},
    "persistence": {...},
    "key_value": {...},
    "pulse": {...},
    "gateway_driver": {...},
    "container_driver": {...},
    "workflow_driver": {...}
}
```
Sections are: `jvm`, `persistence`, `key_value`, `pulse`, `gateway_driver`, `container_driver` and `workflow_driver`.
Requesting sections using parameters: `/api/v1/info?for=jvm&for=persistence`
Main use case is that we don't need often to query all 3rd parties which may be expensive, but just to get information for one part of the system.
For instance only JVM metrics are required for showing Vamp JVM load.
