### ISSUE TITLE
Health check support in DSL

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#709]
It is possible to define health checks using container driver dialects however we should provide direct support:
- validation if it is configured correctly
- fine grained control of deployment cycle https://github.com/magneticio/vamp/issues/72

Vamp should delegate health check to container orchestration engines (DC/OS, Kubernetes) and be able to retrieve health status back.

3rd parties: https://github.com/magneticio/vamp/issues/426

**Comment by olafmol** [comment]
[ ] creation of scheduler health checks on DC/OS, Kubernetes, AWS ECS
[ ] read health status from underlying scheduler and use this metric in our event stream for workflows to use

**Comment by ThomasMeijers** [comment]
### Service Level HealthChecks

A health check can currently be added to blueprints on service level (see branch: [769-HEALTH-CHECKS-DSL](https://github.com/magneticio/vamp/tree/769-HEALTH-CHECKS-DSL)). Each service can have a `health_checks` field that contains zero or more HealthChecks in the form of an array of HealthCheck.

A single HealthCheck is defined with the following fields:

* protocol* - String value that defines the protocol of the request (Either `HTTP` or `HTTPS`) (Standard: `HTTP`).
* path* - String value that defines the path of where the health check requests will be send to (Standard: `/`).
* initial_delay - Time value on how long to wait before make the initial health check request.
* port - The port to which the request should be send to, can be either a number representing the port or a reference (String) to an earlier defined port.
* timeout - Time value on how long a request can timeout before counting the request as a failure.
* interval - Time value that defines the interval of the health check.
* failures - A numerical value that represents the maximum amount of failures before a service is restarted due to being unhealthy.

*optional with a default value

#### Example 1: Minimal Definition in Sava

```yaml
---
name: sava:1.0
gateways:
  9050: sava/webport
clusters:
  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          webport: 8080/http
      scale:
        cpu: 0.2
        memory: 64MB
        instances: 1
      health_checks:
        initial_delay: 10S
        port: webport
        timeout: 5S
        interval: 10S
        failures: 10
```

Path in this example evaluates to `/` and protocol to `HTTP`.

#### Example 2: Multiple Health Checks

```yaml
 health_checks:
  -
     initial_delay: 10S
     port: webport
     timeout: 5S
     interval: 10S
     failures: 10
     protocol: HTTPS
  -
     initial_delay: 1M
     port: webport
     path: /test
     timeout: 10S
     interval: 1M
     failures: 5
     protocol: HTTPS 
```

#### Changes in conf/application.conf
A new value has been introduced in the `application.conf` (as can be seen in the `reference.conf`).
The value `operation.synchronization.check.health-checks` needs to be set to either `true` or `false`, indicating whether changes for this value in blueprints should be checked and redeployed (same behavior as checking for cpu, memory and instances)
