### ISSUE TITLE
Simplifying multiple artifact yaml definition

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#711]
Improvement of https://github.com/magneticio/vamp/issues/698
Instead of just using array of entities:

```yaml
-
  name: ...
  kind: breed
  ...
-
  name: ...
  kind: blueprint
  ...
```
we should support as well standard multiple-docs notation:

```yaml
---
name: ...
kind: breed
...
---
name: ...
kind: blueprint
...
```
