### ISSUE TITLE
Breed deployable as an object: type and definition

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#713]
Now we use schema based approach, a.g. `deployable: docker://magneticio/sava:1.0.0` this should be changed to:
```yaml
deployable:
  type: container/docker
  definition: magneticio/sava:1.0.0
```
By default if only a string is specified `type` will be resolved as `container/docker`.
