### ISSUE TITLE
Breed deployable: 'application/javascript'

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#714]
This allows defining a workflow script as a breed:

```yaml
name: hello-world
deployable: 
  type: 'application/javascript'
  definition: |
    console.log('Hello World!!!');
ports:
  port: 8080/http
```
