### ISSUE TITLE
Sending invalid YAML to /api/v1 causes 500 response

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#724]
For instance `DELETE`:
```yaml
---
kind: breed
name: frontend
----
kind: breed
name: backend
```
It should not fail with `500` but `4xx`.
