### ISSUE TITLE
Support for DSL dialects without content validation

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#73]
Part of https://github.com/magneticio/vamp/issues/71

Cluster and service definition may have dialect specified:

```YAML

name: sava:1.0

endpoints:
  sava.port: 9050

clusters:

  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 80/http
      docker:
        cmd: echo
    marathon:
      env:
        LD_LIBRARY_PATH: "/usr/local/lib/myLib"
```

Service dialect will always override cluster dialect.
There is no validation on content, e.g. in the above example 'cmd' for docker dialect may not be a valid option.
