### ISSUE TITLE
Implement dialects for Docker driver

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#74]
Docker driver doesn't support dialects yet.

**Comment by plamola** [comment]
First use case:

To pull an image from a private registry, the `X-Registry-Auth` header must be set for the `docker pull` command to work. This needs to be set on the breed level, since it is directly linked to the deployable.

https://docs.docker.com/reference/api/docker_remote_api_v1.18/#create-an-image

**Comment by dragoslav** [comment]
Example of setting an environment variable avoiding Vamp DSL:

```YAML
name: mysq

endpoints:
  mysql.port: 9050

clusters:

  mysql:
    services:
      breed:
        name: mysq:5.7.8
        deployable: mysql:5.7.8
        ports:
          port: 3306/tcp

    dialects:
      docker:
        Env: 
        - MYSQL_ROOT_PASSWORD=my-secret-pw
```
