### ISSUE TITLE
can not deploy

### ISSUE THREAD

**Issue by BauRo** [magneticio/vamp#740]
breed:
```
---
name: content:0.1.42
deployable: deployable/content:0.1.42
ports:
  port: 80/http
environment_variables:           
  ENV: ~ 
  SYMFONY_ENV: ~
```
deployment:
```
---
  name: "content"
  environment_variables: 
    application.ENV: "accept"
    application.SYMFONY_ENV: "prod"
  clusters: 
    application: 
      services: 
        - 
          breed: 
            reference: "content:0.1.41"
          scale: 
            cpu: 0.2
            memory: "256MB"
            instances: 2
          marathon: 
            healthChecks: 
              - 
                path: "/monitor/content/health/"
                protocol: "HTTP"
                portIndex: 0
                gracePeriodSeconds: 300
                intervalSeconds: 60
                timeoutSeconds: 20
                maxConsecutiveFailures: 3
                ignoreHttp1xx: false
            uris: 
              - "file:///etc/docker.tar.gz"
```
