### ISSUE TITLE
Test usage of Private Docker registry with Marathon dialects

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#77]
use the "uri" field to provide a username/password for the registry

**Comment by tnolet** [comment]
Tested: This works fine by using the following:
```yaml
      marathon:
       uris:
         -
           "https://some_domain/.dockercfg"
```
