### ISSUE TITLE
Vamp health check example configuration

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#772]
- [ ] Marathon (DC/OS)
- [ ] Kubernetes
- [ ] Rancher

**Comment by iamtew** [comment]
In Marathon HTTP checks will not work when trying to check the API info page at `/api/v1/info?on=jvm`. This seems to be due to some bug in Marathon, but not yet confirmed.

Working health checks using TCP:

Vamp:
```JSON
{
  ...
  "healthChecks": [
    {
      "protocol": "TCP",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "portIndex": 0,
      "maxConsecutiveFailures": 0
    }
  ]
  ...
}
```

Vamp Gateway Agent
```JSON
{
  ...
  "healthChecks": [
    {
      "protocol": "TCP",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "port": 1988,
      "maxConsecutiveFailures": 0
    }
  ]
  ...
}
```

**Comment by iamtew** [comment]
Related issues:
- https://github.com/magneticio/vamp-workflow-agent/issues/3
- https://github.com/magneticio/vamp-gateway-agent/issues/21

**Comment by olafmol** [comment]
Also add health checks for all Vamp components to Kubernetes

**Comment by iamtew** [comment]
Kubernetes health checks looks fairly similar to marathon: https://kubernetes.io/docs/user-guide/walkthrough/k8s201/#health-checking
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-healthcheck
spec:
  containers:
  - name: nginx
    image: nginx
    # defines the health checking
    livenessProbe:
      # an http probe
      httpGet:
        path: /_status/healthz
        port: 80
      # length of time to wait for a pod to initialize
      # after pod startup, before applying health checking
      initialDelaySeconds: 30
      timeoutSeconds: 1
    ports:
    - containerPort: 80
```
