### ISSUE TITLE
unable to create blueprint

### ISSUE THREAD

**Issue by erikpost** [magneticio/vamp#782]
The following blueprint cannot be created in VAMP katana on DCOS 1.7.3:

```
---
name: api-gateway:1.0
gateways:
  8090: api-gateway-service/webport
clusters:
  api-gateway-service:
    services:
      breed:
        name: api-gateway-service:1.0
      env:
        SPRING_CONFIG_LOCATION: 'file:///srv/config/api-gateway/config.yml'
      scale:
        cpu: 0.5
        memory: 1024MB
        instances: 1
      docker:
        volumes:
          "/srv/config": "/srv/config"
      marathon:
        uris:
          - "file:///srv/config/docker.tar.gz"
```

Workaround is to add the environment variable to the breed and then reference the breed in the blueprint.
