### ISSUE TITLE
Trait resolving in blueprints can be done only if all breeds are defined

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#812]
and not when one of them is just referenced.
In the example port `ABCD` may exists in `sava:1.1.0`, so this is still a valid blueprint. 
During deployment this may be invalid if indeed there is no `ABCD` defined in `sava:1.1.0`.

``` yaml
name: sava:1.0
gateways:
  '9050': sava/ABCD
clusters:
  sava:
    services:
    - breed:
        name: sava:1.0.0
        kind: breed
        deployable:
          type: container/docker
          definition: magneticio/sava:1.0.0
        ports:
          webport: 8080/http
    - breed: sava:1.1.0
```

Response: 

```
Gateway port 'sava.ABCD -> Some(9050)' cannot be resolved.
Check if referenced cluster exists and if it has any breed with referenced port name.
```
