### ISSUE TITLE
Environment Variables at Breed Level cause UI Timeout Issues when Deploying, Deleting from UI

### ISSUE THREAD

**Issue by rafarhat** [magneticio/vamp#826]
Stack Version
Vamp: vamp:0.9.1-dcos
DCOS on Azure (ACS): 1.8.4

When breeds are defined with environment variables the number and size of variables seem to cause time out issues when deploying and un-deploying from the VAMP UI. You will have to resort to using the Vamp API in POSTMAN to be able to successfully delete a deployment afterwords..

Repro Steps:

Issue 1

1- Use the blueprint below.
2- Use the UI to add a new deployment.
3- The blueprint should deploy succesfully.
4- If you try to delete the deployment now it should timeout.

Issue 2

1- Use the blueprint below.
2- Use the UI to add a new blueprint.
4- From the blueprint ui deploy the blueprint as sava3 it should timeout.

The only way to delete those deployments now is to Get / deployments/sava2?as_blueprint=true and issue a DELETE with the body.

If you decrease the number of env variables you should start seeing less and less timeout issues.

```yaml
name: sava:2.0
gateways:
  9070: sava/webport
clusters:
  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          webport: 8080/http
        environment_variables:
          SERVICE_BUS_SUBSCRIPTION_NAME: something
          TOPOLOGY_SERVICE_ADDRESS: http://something:10004
          AUTH_AAD_CLIENT_SECRET: '{"id":"https://something/auth-aad-client-secret2"}'
          SERVICE_BUS_TOPIC: choreography
          APP_SERVICE_ENDPOINT: http://something:10013
          SESSION_SECRET: '{"id":"https://something/session-secret"}'
          PREPROVISIONING_ENABLED: 'true'
          SERVER_NAME: something.net
          SUBSCRIPTION_ID: d7c39718-3a3c-4ce8-8ec9-76a6396c0206
          ELASTICSEARCH_HOSTNAME: something:1026
          IOTHUB_CONNECTION_STRING: '{"id":"https://something/iothub-connection-string"}'
          SERVICES: '{"ux_renderer":"http://something:10003","ux_webapi":"http://something:10002","service_app":"http://something:10013","service_topology":"http://something:10004","service_rdx":"http://something:10005","service_search_query":"http://something:10008","service_search_indexer":"http://something:10007","titan":"http://10.20.0.103:10009","service_iothub_management":"http://something:10010","service_simulation":"http://10.20.0.102:10003","service_simulation_proxy":"http://something:10011","service_mashup":"http://something:10014"}'
          REQUEST_RETRY_OPTIONS: '{"retries": 4,"factor": 1,"minTimeout": 100}'
          LOG_LEVEL: trace
          DOCDB_STORAGE: '{"serverUrl":"https://something:443/","databaseId":"something","collectionId":"something"}'
          PROVISIONING_AAD: '{"callbackUrl":"http://keyvault","clientId":"5c61d6a4-3e32-4b13-8b4d-a04ad3ac09a4","endpointUrl":"http://keyvault","tenantId":"e0e146e4-9573-4fe3-8cf2-df033217dc15"}'
          SEARCH_SERVICE_ADDRESS: http://something:10008
          PORT: '3015'
          PROVISIONING_AAD_CLIENT_SECRET: '{"id":"https://something/provisioning-aad-client-secret"}'
          KEYVAULT: '{"clientId":"c5b860a5-5bf5-4577-b104-623d24bdd278","certFile":"/etc/keyvault.pem","certThumbprint":"4cb2a11825691a32b94f9e7dae9816daaecad7db","keyVaultName":"something-int2","resourceGroup":"int_eastus","subscriptionId":"d7ca9418-3a3c-4ce8-8ec9-76a6396c0206"}'
          DOCDB_STORAGE_KEY: '{"id":"https://something/secrets/docdb-storage-key"}'
          ELASTICSEARCH_SERVER_URI: something:1025
          IOTHUB_RETRY_OPTIONS: '{"retries": 10,"factor": 2,"minTimeout": 10000}'
          SERVICE_BUS_CONNECTION_STRING: '{"id":"https://something/secrets/service-bus-connection-string"}'
          WEBAPI: http://something:10002
          AUTH_AAD: '{"callbackUrl":"https://something/api/auth/aad/return","clientId":"de335402-19ff-486e-88a6-7bcccc13a165","endpointUrl":"https://something","tenantId":"1d451ca3-2b49-4479-b04a-5e997739280f"}'
          WEBAPI_SERVICES: '{"services":["something","something","something","something","something"]}'
          CASSANDRA_HOSTNAME: somethings
          DEFAULT_RESOURCE_GROUP: int_westus
          ELASTICSEARCH_INDEX_NAME: search_index
          MIN_PREPROVISIONED_HUBS: '2'
      scale:
        cpu: 0.2       
        memory: 64MB
        instances: 1
```
