### ISSUE TITLE
Synchronization deploy/undeploy timeouts set to 0 should mean no error timeout

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#840]
If deploy/undeploy can't be done within the configured time an error is reported.
If timeout is set to 0, Vamp should keep trying forever.

```yaml
vamp.operation.synchronization.timeout {
  ready-for-deployment: 0 seconds #
  ready-for-undeployment: 0 seconds #
}
```
