### ISSUE TITLE
Explicit creation of gateways fails in Katana

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#848]
f.e. running a recipe with a seperate gateway creation step, or using the UI to add this to a sava example:
```yaml
---
name: sava  # name of our gateway
port: 9050/http           
routes:
  sava/sava/webport:   
    weight: 100%          
```
doesn't throw any error, but the gateway isn't created and doesn't show up in the UI. The UI gives a positive feedback though.

Adding the gateway in the blueprint works fine though, f.e. the first Sava tutorial example works fine.

Also this example works:
```yaml
name: mesos
port: 8080/http
sticky: route

routes:
  "[192.168.99.100:5050]":
    weight: 50%
  "[localhost:5050]":
    weight: 50%
```
