### ISSUE TITLE
Scheduling services/workflows on all nodes 

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#854]
If number of instances is set to `*`, e.g. custom scale as:

```yaml
name: run_on_all_medium
cpu: 1
memory: 1GB
instances: *
```
This is directly supported by Kubernetes and Rancher.
