### ISSUE TITLE
Vamp server as reverse proxy to Vamp gateways

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#884]
Endpoints depend on gateway names:
- `segment1`                   ⇒ `/proxy/segment1/`, e.g. `/proxy/sava/`
- `segment1/segment2` ⇒ `/proxy/segment1/segment2/`, e.g. `/proxy/sava/9050/`
- `segment1/segment2/segment3` ⇒ `/proxy/segment1/segment2/segment3/`, e.g. `/proxy/sava/sava/webport/`

Implementation for:
- [x] HTTP
- [x] WebSockets

In addition we could later support TCP and HTTPS (separate issues).

**HTTP reverse proxy example - `sava`**

- run Vamp quick start and deploy `sava` with `9050` gateway
- open `http://192.168.99.100:8080/proxy/sava/9050/`

**HTTP reverse proxy example - access to Marathon UI/API**

- run Vamp quick start (assuming Vamp URL is http://192.168.99.100:8080) and create a new gateway:
```yaml
name: marathon
port: 9010
routes: "[192.168.99.100:9090]"
```
- open `http://192.168.99.100:8080/proxy/marathon/`

**HTTP & WebSocket reverse proxy example - Vamp UI within Vamp UI**

- run Vamp quick start (assuming Vamp URL is http://192.168.99.100:8080) and create a new gateway:
```yaml
name: vamp
port: 9020
routes: "[192.168.99.100:8080]"
```
- open `http://192.168.99.100:8080/proxy/vamp/`
