### ISSUE TITLE
Add "metadata" to all artifacts

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#890]
Example:
```yaml
name: health
kind: breed
metadata:
  description: simple health calculation
  labels: 
    vamp: breed
  annotation:
    essential: true
...
```

Everything under `metadata` is optional and not validated bu Vamp - treated as a simple key/value map.
