### ISSUE TITLE
arguments are not passed in marathon dialect blocks

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#896]
this is working marathon JSON:

```
{
  "volumes": null,
  "id": "/echo",
  "cmd": null,
  "args": [
    "-text=\"olaf\""
  ],
  "user": null,
  "env": null,
  "instances": 1,
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "gpus": 0,
  "executor": null,
  "constraints": null,
  "fetch": null,
  "storeUrls": null,
  "backoffSeconds": 1,
  "backoffFactor": 1.15,
  "maxLaunchDelaySeconds": 3600,
  "container": {
    "docker": {
      "image": "hashicorp/http-echo:0.2.1",
      "forcePullImage": true,
      "privileged": true,
      "network": "HOST"
    }
  },
  "healthChecks": null,
  "readinessChecks": null,
  "dependencies": null,
  "upgradeStrategy": {
    "minimumHealthCapacity": 1,
    "maximumOverCapacity": 1
  },
  "labels": null,
  "acceptedResourceRoles": null,
  "residency": null,
  "secrets": null,
  "taskKillGracePeriodSeconds": null,
  "portDefinitions": [
    {
      "protocol": "tcp",
      "port": 10000
    }
  ],
  "requirePorts": false
}
```

(note the args block)

when i deploy this blueprint the container fails with the message that it's missing the "text" argument, so it seems it's not parsed/passed correctly by Vamp dialects parser:

```
---
name: echo
gateways:
  5678: echo/webport
clusters:
  echo:
    services:
      breed:
        name: echo:0.2.1
        deployable: hashicorp/http-echo:0.2.1
        ports:
          webport: 5678/http
      scale:
        cpu: 1       
        memory: 128MB
        instances: 1
      marathon:
        args: [
          "-text=\"olaf\""
        ]
```
