### ISSUE TITLE
Using Vamp configuration values in breed traits

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#906]
Similar to https://github.com/magneticio/vamp/issues/36 and https://github.com/magneticio/vamp/issues/862

In the following example `${config://vamp.url}` is read from Vamp configuration:

```yaml
name: vamp-runner
gateways:
  8088: vamp-runner/port
clusters:
  vamp-runner:
    services:
      breed:
        name: vamp-runner:katana
        deployable: magneticio/vamp-runner:katana
        ports:
          port: 8088/http
        environment_variables:
          VAMP_RUNNER_API_URL: ${config://vamp.url}
      scale:
        cpu: 0.2       
        memory: 256MB
        instances: 1
```

In order to use configuration values, reference schema needs to be: `conf`, `config` or `configuration`.
