### ISSUE TITLE
"serviceHealth" -> "service_health" serialization

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#918]
Currently:

```yaml
serviceHealth:
  staged: 0
  running: 1
  healthy: 1
  unhealthy: 0
```
