### ISSUE TITLE
time based workflow validation error

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#920]
when defining a time based workflow like this (based on our documentation examples, Vamp 093 docker quickstart on Mac OS X):

```
schedule:
  time:
    period: P1Y2M3DT4H5M6S
    start: now # or e.g. start: 2016-12-03T08:15:30Z
    repeat: 10
```

the editor show the following validation error:

```
Unexpected type for path 'start'.
 in 'reader', line 10, column 10:
        start: now # or e.g. start: 2016-12-0 ... 
             ^
```

**Comment by gggina** [comment]
To add to this. Specifying an ISO8601 start time removes the validation error in the editor and allows the workflow to be saved:
```
schedule:
  time:
    period: P1Y2M3DT4H5M6S
    start: 2017-03-01T08:15:30
    repeat: 10
```

However, the workflow is not created and the Vamp log gives an error every 3 seconds: 
```
10:20:19.615	ERROR	io.vamp.common.notification.Notification	Unexpected type for path 'start'.
10:20:22.618	ERROR	io.vamp.common.notification.Notification	Unexpected type for path 'start'.
10:20:25.619	ERROR	io.vamp.common.notification.Notification	Unexpected type for path 'start'.
```
