### ISSUE TITLE
Deployment level dialect

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#922]
Blueprint/deployment example:
```yaml
---
name: sava:1.0
gateways:
  9050: sava/webport
clusters:
  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          webport: 8080/http
dialect:
  marathon:
    labels:
      owner: "buffy the vamp slayer"
```
