### ISSUE TITLE
Workflow dialects

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#925]
Similar to deployment/cluster dialects:
```yaml
name    : log
breed   : log
schedule: daemon
dialect:
  marathon:
    labels:
      foo: "bar"
      name: ${workflow}
```
