### ISSUE TITLE
Dialect JSON serialisation should be without any format conversion.

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#94]
```YAML
marathon:
  env:
    LD_LIBRARY_PATH: "/usr/local/lib/myLib"
```
should not result to:

```YAML
marathon:
  env:
    ld_library_path: "/usr/local/lib/myLib"
```
