### ISSUE TITLE
boolean config values set through environment variables are set as string

### ISSUE THREAD

**Issue by RoelVanNyen** [magneticio/vamp#940]
If you try to set the environment variable "VAMP_OPERATION_GATEWAY_VIRTUAL_HOSTS_ENABLED": "false"
It results in:

```
operation:
    health:
      window: 30 seconds
    reload-configuration-delay: 2s
    deployment:
      scale:
        instances: 1
        memory: 256MB
        cpu: 0.2
      arguments:
      - privileged=true
    gateway:
      virtual-hosts:
        formats:
          deployment-cluster-port: $port.$cluster.$deployment.vamp
          deployment-port: $port.$deployment.vamp
          gateway: $gateway.vamp
        enabled: 'false'
```

Please notice the single quotes around 'true' for the key enabled.

I expect it to be just enabled: false

I`m not sure if it affects the actual behaviour.
