### ISSUE TITLE
Option to create/update an artifact using template(s)

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#968]
## Features
- new artifact and CRUD endpoints: `templates`
- single or multiple (list) import references - applied sequentially, thus the second is merged on top of the first
- each import reference may contain type `{type}/{name}`, otherwise default type is `templates`, e.g. `blueprints/sava:1.0`, `templates/sava` (or just `sava`)

### Template:
```yaml
name: sava_breed
kind: template
definition:
  ports:
    webport: 8080/http
  environment_variables:
    SAVA_DEBUG: 'false'
```
using it:
```yaml
name: sava:1.0.0
kind: breed
import: sava_breed # equivalent to templates/sava_breed
```
### Multiple imports:
```yaml
name: sava:1.0.0
kind: breed
import:
- template1
- breeds/sava:1.1 # importing from breed (non-template) artifact
```

### Update based on an older artifact:
```yaml
name: sava:1.1.0
import: breeds/sava:1.0.0 # importing 1.0.0
deployable: magneticio/sava:1.1.0 # overriding just the image
```
