### ISSUE TITLE
[Vamp095-katana] Applying split routing in blueprint does not deploy correctly

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#970]
when deploying the following blueprint on 095 katana on DCOS the deployment fails, starting only 1 service, and having the other one in deploying (in marathon:waiting) mode, as well as the internal gateway stuck in deploying mode. This works fine in Vamp 094

```
---
name: sava:1.0
gateways:
  9050: sava/webport
clusters:
  sava:
    gateways:
      routes:
        sava:1.0.0:
          weight: 50%  # weight in percentage
        sava:1.1.0:
          weight: 50%
    services: # services is now a list of breeds
      -
        breed:
          name: sava:1.0.0
          deployable: magneticio/sava:1.0.0
          ports:
            webport: 8080/http
        scale:
          cpu: 0.2
          memory: 64MB
          instances: 1
      -
        breed:
          name: sava:1.1.0 # a new version of our service
          deployable: magneticio/sava:1.1.0
          ports:
            webport: 8080/http
        scale:
          cpu: 0.2
          memory: 64MB
          instances: 1
```
