### ISSUE TITLE
Accessing triggering event within resulted workflow execution

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#973]
Serialized event (JSON + Base64) should be available as an environment variable.
Example:

```yaml
name: event
kind: workflow
breed:
  reference: event
schedule:
  event:
    tags:
    - run:event
environment_variables:
  VAMP_WORKFLOW_DATA: ${data} # using custom env to get the event (data)
  VAMP_WORKFLOW_EXECUTION_PERIOD: '0'
  VAMP_WORKFLOW_EXECUTION_TIMEOUT: '5'
```
```yaml
name: event
kind: breed
deployable:
  type: application/javascript
  definition: |-
    let vamp = require('vamp-node-client');
    let data = '';
    let api = new vamp.Api();

    if (process.env.VAMP_WORKFLOW_DATA) {
      let event = Buffer.from(process.env.VAMP_WORKFLOW_DATA, 'base64').toString('utf8');
      data = event ? JSON.parse(event).tags : data;
    }
    api.event(['event:response'], data);
```
